// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

/**
 * <pre>
 * Balance to Limit
 * </pre>
 *
 * Protobuf type {@code grpc_limits.Balance}
 */
public  final class Balance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc_limits.Balance)
    BalanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Balance.newBuilder() to construct.
  private Balance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Balance() {
    availableAmount_ = 0D;
    usedAmount_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Balance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (startDate_ != null) {
              subBuilder = startDate_.toBuilder();
            }
            startDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(startDate_);
              startDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (endDate_ != null) {
              subBuilder = endDate_.toBuilder();
            }
            endDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(endDate_);
              endDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 25: {

            availableAmount_ = input.readDouble();
            break;
          }
          case 33: {

            usedAmount_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_Balance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_Balance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.client.app.fxLimit.Balance.class, grpc.client.app.fxLimit.Balance.Builder.class);
  }

  public static final int STARTDATE_FIELD_NUMBER = 1;
  private com.google.protobuf.Timestamp startDate_;
  /**
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  public boolean hasStartDate() {
    return startDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  public com.google.protobuf.Timestamp getStartDate() {
    return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
    return getStartDate();
  }

  public static final int ENDDATE_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp endDate_;
  /**
   * <code>.google.protobuf.Timestamp endDate = 2;</code>
   */
  public boolean hasEndDate() {
    return endDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp endDate = 2;</code>
   */
  public com.google.protobuf.Timestamp getEndDate() {
    return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp endDate = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
    return getEndDate();
  }

  public static final int AVAILABLEAMOUNT_FIELD_NUMBER = 3;
  private double availableAmount_;
  /**
   * <code>double availableAmount = 3;</code>
   */
  public double getAvailableAmount() {
    return availableAmount_;
  }

  public static final int USEDAMOUNT_FIELD_NUMBER = 4;
  private double usedAmount_;
  /**
   * <code>double usedAmount = 4;</code>
   */
  public double getUsedAmount() {
    return usedAmount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startDate_ != null) {
      output.writeMessage(1, getStartDate());
    }
    if (endDate_ != null) {
      output.writeMessage(2, getEndDate());
    }
    if (availableAmount_ != 0D) {
      output.writeDouble(3, availableAmount_);
    }
    if (usedAmount_ != 0D) {
      output.writeDouble(4, usedAmount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStartDate());
    }
    if (endDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getEndDate());
    }
    if (availableAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, availableAmount_);
    }
    if (usedAmount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, usedAmount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.client.app.fxLimit.Balance)) {
      return super.equals(obj);
    }
    grpc.client.app.fxLimit.Balance other = (grpc.client.app.fxLimit.Balance) obj;

    boolean result = true;
    result = result && (hasStartDate() == other.hasStartDate());
    if (hasStartDate()) {
      result = result && getStartDate()
          .equals(other.getStartDate());
    }
    result = result && (hasEndDate() == other.hasEndDate());
    if (hasEndDate()) {
      result = result && getEndDate()
          .equals(other.getEndDate());
    }
    result = result && (
        java.lang.Double.doubleToLongBits(getAvailableAmount())
        == java.lang.Double.doubleToLongBits(
            other.getAvailableAmount()));
    result = result && (
        java.lang.Double.doubleToLongBits(getUsedAmount())
        == java.lang.Double.doubleToLongBits(
            other.getUsedAmount()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStartDate()) {
      hash = (37 * hash) + STARTDATE_FIELD_NUMBER;
      hash = (53 * hash) + getStartDate().hashCode();
    }
    if (hasEndDate()) {
      hash = (37 * hash) + ENDDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEndDate().hashCode();
    }
    hash = (37 * hash) + AVAILABLEAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAvailableAmount()));
    hash = (37 * hash) + USEDAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getUsedAmount()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.client.app.fxLimit.Balance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.Balance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.client.app.fxLimit.Balance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.client.app.fxLimit.Balance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.client.app.fxLimit.Balance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Balance to Limit
   * </pre>
   *
   * Protobuf type {@code grpc_limits.Balance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc_limits.Balance)
      grpc.client.app.fxLimit.BalanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_Balance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_Balance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.client.app.fxLimit.Balance.class, grpc.client.app.fxLimit.Balance.Builder.class);
    }

    // Construct using grpc.client.app.fxLimit.Balance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (startDateBuilder_ == null) {
        startDate_ = null;
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }
      if (endDateBuilder_ == null) {
        endDate_ = null;
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }
      availableAmount_ = 0D;

      usedAmount_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_Balance_descriptor;
    }

    @java.lang.Override
    public grpc.client.app.fxLimit.Balance getDefaultInstanceForType() {
      return grpc.client.app.fxLimit.Balance.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.client.app.fxLimit.Balance build() {
      grpc.client.app.fxLimit.Balance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.client.app.fxLimit.Balance buildPartial() {
      grpc.client.app.fxLimit.Balance result = new grpc.client.app.fxLimit.Balance(this);
      if (startDateBuilder_ == null) {
        result.startDate_ = startDate_;
      } else {
        result.startDate_ = startDateBuilder_.build();
      }
      if (endDateBuilder_ == null) {
        result.endDate_ = endDate_;
      } else {
        result.endDate_ = endDateBuilder_.build();
      }
      result.availableAmount_ = availableAmount_;
      result.usedAmount_ = usedAmount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.client.app.fxLimit.Balance) {
        return mergeFrom((grpc.client.app.fxLimit.Balance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.client.app.fxLimit.Balance other) {
      if (other == grpc.client.app.fxLimit.Balance.getDefaultInstance()) return this;
      if (other.hasStartDate()) {
        mergeStartDate(other.getStartDate());
      }
      if (other.hasEndDate()) {
        mergeEndDate(other.getEndDate());
      }
      if (other.getAvailableAmount() != 0D) {
        setAvailableAmount(other.getAvailableAmount());
      }
      if (other.getUsedAmount() != 0D) {
        setUsedAmount(other.getUsedAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.client.app.fxLimit.Balance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.client.app.fxLimit.Balance) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Timestamp startDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> startDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public boolean hasStartDate() {
      return startDateBuilder_ != null || startDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public com.google.protobuf.Timestamp getStartDate() {
      if (startDateBuilder_ == null) {
        return startDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      } else {
        return startDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder setStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startDate_ = value;
        onChanged();
      } else {
        startDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder setStartDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (startDateBuilder_ == null) {
        startDate_ = builderForValue.build();
        onChanged();
      } else {
        startDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder mergeStartDate(com.google.protobuf.Timestamp value) {
      if (startDateBuilder_ == null) {
        if (startDate_ != null) {
          startDate_ =
            com.google.protobuf.Timestamp.newBuilder(startDate_).mergeFrom(value).buildPartial();
        } else {
          startDate_ = value;
        }
        onChanged();
      } else {
        startDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public Builder clearStartDate() {
      if (startDateBuilder_ == null) {
        startDate_ = null;
        onChanged();
      } else {
        startDate_ = null;
        startDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public com.google.protobuf.Timestamp.Builder getStartDateBuilder() {
      
      onChanged();
      return getStartDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder() {
      if (startDateBuilder_ != null) {
        return startDateBuilder_.getMessageOrBuilder();
      } else {
        return startDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : startDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp startDate = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getStartDateFieldBuilder() {
      if (startDateBuilder_ == null) {
        startDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getStartDate(),
                getParentForChildren(),
                isClean());
        startDate_ = null;
      }
      return startDateBuilder_;
    }

    private com.google.protobuf.Timestamp endDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> endDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public boolean hasEndDate() {
      return endDateBuilder_ != null || endDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public com.google.protobuf.Timestamp getEndDate() {
      if (endDateBuilder_ == null) {
        return endDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      } else {
        return endDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public Builder setEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endDate_ = value;
        onChanged();
      } else {
        endDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public Builder setEndDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (endDateBuilder_ == null) {
        endDate_ = builderForValue.build();
        onChanged();
      } else {
        endDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public Builder mergeEndDate(com.google.protobuf.Timestamp value) {
      if (endDateBuilder_ == null) {
        if (endDate_ != null) {
          endDate_ =
            com.google.protobuf.Timestamp.newBuilder(endDate_).mergeFrom(value).buildPartial();
        } else {
          endDate_ = value;
        }
        onChanged();
      } else {
        endDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public Builder clearEndDate() {
      if (endDateBuilder_ == null) {
        endDate_ = null;
        onChanged();
      } else {
        endDate_ = null;
        endDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getEndDateBuilder() {
      
      onChanged();
      return getEndDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder() {
      if (endDateBuilder_ != null) {
        return endDateBuilder_.getMessageOrBuilder();
      } else {
        return endDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : endDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp endDate = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getEndDateFieldBuilder() {
      if (endDateBuilder_ == null) {
        endDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getEndDate(),
                getParentForChildren(),
                isClean());
        endDate_ = null;
      }
      return endDateBuilder_;
    }

    private double availableAmount_ ;
    /**
     * <code>double availableAmount = 3;</code>
     */
    public double getAvailableAmount() {
      return availableAmount_;
    }
    /**
     * <code>double availableAmount = 3;</code>
     */
    public Builder setAvailableAmount(double value) {
      
      availableAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double availableAmount = 3;</code>
     */
    public Builder clearAvailableAmount() {
      
      availableAmount_ = 0D;
      onChanged();
      return this;
    }

    private double usedAmount_ ;
    /**
     * <code>double usedAmount = 4;</code>
     */
    public double getUsedAmount() {
      return usedAmount_;
    }
    /**
     * <code>double usedAmount = 4;</code>
     */
    public Builder setUsedAmount(double value) {
      
      usedAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double usedAmount = 4;</code>
     */
    public Builder clearUsedAmount() {
      
      usedAmount_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc_limits.Balance)
  }

  // @@protoc_insertion_point(class_scope:grpc_limits.Balance)
  private static final grpc.client.app.fxLimit.Balance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.client.app.fxLimit.Balance();
  }

  public static grpc.client.app.fxLimit.Balance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Balance>
      PARSER = new com.google.protobuf.AbstractParser<Balance>() {
    @java.lang.Override
    public Balance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Balance(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Balance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Balance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.client.app.fxLimit.Balance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

