// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

public interface BalanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.Balance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  boolean hasStartDate();
  /**
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  com.google.protobuf.Timestamp getStartDate();
  /**
   * <code>.google.protobuf.Timestamp startDate = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartDateOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp endDate = 2;</code>
   */
  boolean hasEndDate();
  /**
   * <code>.google.protobuf.Timestamp endDate = 2;</code>
   */
  com.google.protobuf.Timestamp getEndDate();
  /**
   * <code>.google.protobuf.Timestamp endDate = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getEndDateOrBuilder();

  /**
   * <code>double availableAmount = 3;</code>
   */
  double getAvailableAmount();

  /**
   * <code>double usedAmount = 4;</code>
   */
  double getUsedAmount();
}
