// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

public interface CurrencyAmountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.CurrencyAmount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string currency = 1;</code>
   */
  java.lang.String getCurrency();
  /**
   * <code>string currency = 1;</code>
   */
  com.google.protobuf.ByteString
      getCurrencyBytes();

  /**
   * <code>double amount = 2;</code>
   */
  double getAmount();
}
