// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc_limits.Authorship authorship = 1;</code>
   */
  boolean hasAuthorship();
  /**
   * <code>.grpc_limits.Authorship authorship = 1;</code>
   */
  grpc.client.app.fxLimit.Authorship getAuthorship();
  /**
   * <code>.grpc_limits.Authorship authorship = 1;</code>
   */
  grpc.client.app.fxLimit.AuthorshipOrBuilder getAuthorshipOrBuilder();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  boolean hasDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.Timestamp getDate();
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateOrBuilder();

  /**
   * <code>.grpc_limits.EventType type = 4;</code>
   */
  int getTypeValue();
  /**
   * <code>.grpc_limits.EventType type = 4;</code>
   */
  grpc.client.app.fxLimit.EventType getType();

  /**
   * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
   */
  boolean hasExpirationDate();
  /**
   * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
   */
  com.google.protobuf.Timestamp getExpirationDate();
  /**
   * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder();

  /**
   * <code>.grpc_limits.TransactionType transactionType = 6;</code>
   */
  int getTransactionTypeValue();
  /**
   * <code>.grpc_limits.TransactionType transactionType = 6;</code>
   */
  grpc.client.app.fxLimit.TransactionType getTransactionType();

  /**
   * <code>double amount = 7;</code>
   */
  double getAmount();
}
