// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

public final class FxLimit {
  private FxLimit() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_GetLimitsByKeyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_GetLimitsByKeyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_GetLimitsByKeyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_GetLimitsByKeyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_LimitKey_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_LimitKey_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_Limit_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_Limit_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_Authorship_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_Authorship_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_CurrencyAmount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_CurrencyAmount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_Balance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_Balance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_Version_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_Version_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_limits_Paginator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_limits_Paginator_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rfxLimit.proto\022\013grpc_limits\032\037google/pro" +
      "tobuf/timestamp.proto\"\236\001\n\025GetLimitsByKey" +
      "Request\022\'\n\010limitKey\030\001 \001(\0132\025.grpc_limits." +
      "LimitKey\0221\n\rrevokedFilter\030\002 \001(\0162\032.grpc_l" +
      "imits.RevokedFilter\022)\n\tpaginator\030\003 \001(\0132\026" +
      ".grpc_limits.Paginator\"<\n\026GetLimitsByKey" +
      "Response\022\"\n\006limits\030\001 \003(\0132\022.grpc_limits.L" +
      "imit\"\227\001\n\010LimitKey\022\030\n\020customerDocument\030\001 " +
      "\001(\t\022\021\n\tpartnerID\030\002 \001(\t\022\017\n\007offerID\030\003 \001(\t\022" +
      "\'\n\010category\030\004 \001(\0162\025.grpc_limits.Category" +
      "\022$\n\004type\030\005 \001(\0162\026.grpc_limits.LimitType\"\364" +
      "\001\n\005Limit\022\'\n\010limitKey\030\001 \001(\0132\025.grpc_limits" +
      ".LimitKey\022\n\n\002id\030\002 \001(\t\0223\n\016currencyAmount\030" +
      "\003 \001(\0132\033.grpc_limits.CurrencyAmount\022%\n\007ba" +
      "lance\030\004 \001(\0132\024.grpc_limits.Balance\022%\n\007ver" +
      "sion\030\005 \001(\0132\024.grpc_limits.Version\022\017\n\007revo" +
      "ked\030\006 \001(\010\022\"\n\006events\030\007 \003(\0132\022.grpc_limits." +
      "Event\"-\n\nAuthorship\022\016\n\006author\030\001 \001(\t\022\017\n\007c" +
      "omment\030\002 \001(\t\"2\n\016CurrencyAmount\022\020\n\010curren" +
      "cy\030\001 \001(\t\022\016\n\006amount\030\002 \001(\001\"\222\001\n\007Balance\022-\n\t" +
      "startDate\030\001 \001(\0132\032.google.protobuf.Timest" +
      "amp\022+\n\007endDate\030\002 \001(\0132\032.google.protobuf.T" +
      "imestamp\022\027\n\017availableAmount\030\003 \001(\001\022\022\n\nuse" +
      "dAmount\030\004 \001(\001\"\213\002\n\005Event\022+\n\nauthorship\030\001 " +
      "\001(\0132\027.grpc_limits.Authorship\022\n\n\002id\030\002 \001(\t" +
      "\022(\n\004date\030\003 \001(\0132\032.google.protobuf.Timesta" +
      "mp\022$\n\004type\030\004 \001(\0162\026.grpc_limits.EventType" +
      "\0222\n\016expirationDate\030\005 \001(\0132\032.google.protob" +
      "uf.Timestamp\0225\n\017transactionType\030\006 \001(\0162\034." +
      "grpc_limits.TransactionType\022\016\n\006amount\030\007 " +
      "\001(\001\"\245\001\n\007Version\022\021\n\tcreatedBy\030\001 \001(\t\022-\n\tcr" +
      "eatedAt\030\002 \001(\0132\032.google.protobuf.Timestam" +
      "p\022\025\n\rlastUpdatedBy\030\003 \001(\t\0221\n\rlastUpdatedA" +
      "t\030\004 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006n" +
      "umber\030\005 \001(\005\"*\n\tPaginator\022\r\n\005limit\030\001 \001(\003\022" +
      "\016\n\006offset\030\002 \001(\003*O\n\010Category\022\024\n\020UNKNOWN_C" +
      "ATEGORY\020\000\022\026\n\022FINANCIAL_CAPACITY\020\001\022\025\n\021NAT" +
      "IONAL_TRANSFER\020\002*y\n\tLimitType\022\020\n\014UNKNOWN" +
      "_TYPE\020\000\022\020\n\014BUY_CURRENCY\020\001\022\021\n\rSELL_CURREN" +
      "CY\020\002\022\n\n\006IMPORT\020\003\022\n\n\006EXPORT\020\004\022\013\n\007GENERAL\020" +
      "\005\022\007\n\003TED\020\006\022\007\n\003PIX\020\007*Y\n\017TransactionType\022\027" +
      "\n\023UNKNOWN_TRANSACTION\020\000\022\025\n\021DEBIT_TRANSAC" +
      "TION\020\001\022\026\n\022CREDIT_TRANSACTION\020\002*|\n\tEventT" +
      "ype\022\016\n\nALL_EVENTS\020\000\022\020\n\014CREATE_LIMIT\020\001\022\031\n" +
      "\025INCREASE_AMOUNT_LIMIT\020\002\022\017\n\013RENEW_LIMIT\020" +
      "\003\022\020\n\014REVOKE_LIMIT\020\004\022\017\n\013TRANSACTION\020\005*=\n\r" +
      "RevokedFilter\022\016\n\nALL_LIMITS\020\000\022\013\n\007REVOKED" +
      "\020\001\022\017\n\013NOT_REVOKED\020\0022i\n\014LimitService\022Y\n\016G" +
      "etLimitsByKey\022\".grpc_limits.GetLimitsByK" +
      "eyRequest\032#.grpc_limits.GetLimitsByKeyRe" +
      "sponseB*\n\027grpc.client.app.fxLimitB\007FxLim" +
      "itP\001\242\002\003RTGb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_grpc_limits_GetLimitsByKeyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_limits_GetLimitsByKeyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_GetLimitsByKeyRequest_descriptor,
        new java.lang.String[] { "LimitKey", "RevokedFilter", "Paginator", });
    internal_static_grpc_limits_GetLimitsByKeyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_limits_GetLimitsByKeyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_GetLimitsByKeyResponse_descriptor,
        new java.lang.String[] { "Limits", });
    internal_static_grpc_limits_LimitKey_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_grpc_limits_LimitKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_LimitKey_descriptor,
        new java.lang.String[] { "CustomerDocument", "PartnerID", "OfferID", "Category", "Type", });
    internal_static_grpc_limits_Limit_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_grpc_limits_Limit_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_Limit_descriptor,
        new java.lang.String[] { "LimitKey", "Id", "CurrencyAmount", "Balance", "Version", "Revoked", "Events", });
    internal_static_grpc_limits_Authorship_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_grpc_limits_Authorship_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_Authorship_descriptor,
        new java.lang.String[] { "Author", "Comment", });
    internal_static_grpc_limits_CurrencyAmount_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_grpc_limits_CurrencyAmount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_CurrencyAmount_descriptor,
        new java.lang.String[] { "Currency", "Amount", });
    internal_static_grpc_limits_Balance_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_grpc_limits_Balance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_Balance_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "AvailableAmount", "UsedAmount", });
    internal_static_grpc_limits_Event_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_grpc_limits_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_Event_descriptor,
        new java.lang.String[] { "Authorship", "Id", "Date", "Type", "ExpirationDate", "TransactionType", "Amount", });
    internal_static_grpc_limits_Version_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_grpc_limits_Version_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_Version_descriptor,
        new java.lang.String[] { "CreatedBy", "CreatedAt", "LastUpdatedBy", "LastUpdatedAt", "Number", });
    internal_static_grpc_limits_Paginator_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_grpc_limits_Paginator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_limits_Paginator_descriptor,
        new java.lang.String[] { "Limit", "Offset", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
