// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

public interface GetLimitsByKeyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.GetLimitsByKeyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  boolean hasLimitKey();
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  grpc.client.app.fxLimit.LimitKey getLimitKey();
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  grpc.client.app.fxLimit.LimitKeyOrBuilder getLimitKeyOrBuilder();

  /**
   * <code>.grpc_limits.RevokedFilter revokedFilter = 2;</code>
   */
  int getRevokedFilterValue();
  /**
   * <code>.grpc_limits.RevokedFilter revokedFilter = 2;</code>
   */
  grpc.client.app.fxLimit.RevokedFilter getRevokedFilter();

  /**
   * <code>.grpc_limits.Paginator paginator = 3;</code>
   */
  boolean hasPaginator();
  /**
   * <code>.grpc_limits.Paginator paginator = 3;</code>
   */
  grpc.client.app.fxLimit.Paginator getPaginator();
  /**
   * <code>.grpc_limits.Paginator paginator = 3;</code>
   */
  grpc.client.app.fxLimit.PaginatorOrBuilder getPaginatorOrBuilder();
}
