// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

/**
 * <pre>
 * The response to get limits by key
 * </pre>
 *
 * Protobuf type {@code grpc_limits.GetLimitsByKeyResponse}
 */
public  final class GetLimitsByKeyResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc_limits.GetLimitsByKeyResponse)
    GetLimitsByKeyResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetLimitsByKeyResponse.newBuilder() to construct.
  private GetLimitsByKeyResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetLimitsByKeyResponse() {
    limits_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetLimitsByKeyResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              limits_ = new java.util.ArrayList<grpc.client.app.fxLimit.Limit>();
              mutable_bitField0_ |= 0x00000001;
            }
            limits_.add(
                input.readMessage(grpc.client.app.fxLimit.Limit.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        limits_ = java.util.Collections.unmodifiableList(limits_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_GetLimitsByKeyResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_GetLimitsByKeyResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.client.app.fxLimit.GetLimitsByKeyResponse.class, grpc.client.app.fxLimit.GetLimitsByKeyResponse.Builder.class);
  }

  public static final int LIMITS_FIELD_NUMBER = 1;
  private java.util.List<grpc.client.app.fxLimit.Limit> limits_;
  /**
   * <code>repeated .grpc_limits.Limit limits = 1;</code>
   */
  public java.util.List<grpc.client.app.fxLimit.Limit> getLimitsList() {
    return limits_;
  }
  /**
   * <code>repeated .grpc_limits.Limit limits = 1;</code>
   */
  public java.util.List<? extends grpc.client.app.fxLimit.LimitOrBuilder> 
      getLimitsOrBuilderList() {
    return limits_;
  }
  /**
   * <code>repeated .grpc_limits.Limit limits = 1;</code>
   */
  public int getLimitsCount() {
    return limits_.size();
  }
  /**
   * <code>repeated .grpc_limits.Limit limits = 1;</code>
   */
  public grpc.client.app.fxLimit.Limit getLimits(int index) {
    return limits_.get(index);
  }
  /**
   * <code>repeated .grpc_limits.Limit limits = 1;</code>
   */
  public grpc.client.app.fxLimit.LimitOrBuilder getLimitsOrBuilder(
      int index) {
    return limits_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < limits_.size(); i++) {
      output.writeMessage(1, limits_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < limits_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, limits_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.client.app.fxLimit.GetLimitsByKeyResponse)) {
      return super.equals(obj);
    }
    grpc.client.app.fxLimit.GetLimitsByKeyResponse other = (grpc.client.app.fxLimit.GetLimitsByKeyResponse) obj;

    boolean result = true;
    result = result && getLimitsList()
        .equals(other.getLimitsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getLimitsCount() > 0) {
      hash = (37 * hash) + LIMITS_FIELD_NUMBER;
      hash = (53 * hash) + getLimitsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.client.app.fxLimit.GetLimitsByKeyResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response to get limits by key
   * </pre>
   *
   * Protobuf type {@code grpc_limits.GetLimitsByKeyResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc_limits.GetLimitsByKeyResponse)
      grpc.client.app.fxLimit.GetLimitsByKeyResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_GetLimitsByKeyResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_GetLimitsByKeyResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.client.app.fxLimit.GetLimitsByKeyResponse.class, grpc.client.app.fxLimit.GetLimitsByKeyResponse.Builder.class);
    }

    // Construct using grpc.client.app.fxLimit.GetLimitsByKeyResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLimitsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (limitsBuilder_ == null) {
        limits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        limitsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.client.app.fxLimit.FxLimit.internal_static_grpc_limits_GetLimitsByKeyResponse_descriptor;
    }

    @java.lang.Override
    public grpc.client.app.fxLimit.GetLimitsByKeyResponse getDefaultInstanceForType() {
      return grpc.client.app.fxLimit.GetLimitsByKeyResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.client.app.fxLimit.GetLimitsByKeyResponse build() {
      grpc.client.app.fxLimit.GetLimitsByKeyResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.client.app.fxLimit.GetLimitsByKeyResponse buildPartial() {
      grpc.client.app.fxLimit.GetLimitsByKeyResponse result = new grpc.client.app.fxLimit.GetLimitsByKeyResponse(this);
      int from_bitField0_ = bitField0_;
      if (limitsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          limits_ = java.util.Collections.unmodifiableList(limits_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.limits_ = limits_;
      } else {
        result.limits_ = limitsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.client.app.fxLimit.GetLimitsByKeyResponse) {
        return mergeFrom((grpc.client.app.fxLimit.GetLimitsByKeyResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.client.app.fxLimit.GetLimitsByKeyResponse other) {
      if (other == grpc.client.app.fxLimit.GetLimitsByKeyResponse.getDefaultInstance()) return this;
      if (limitsBuilder_ == null) {
        if (!other.limits_.isEmpty()) {
          if (limits_.isEmpty()) {
            limits_ = other.limits_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLimitsIsMutable();
            limits_.addAll(other.limits_);
          }
          onChanged();
        }
      } else {
        if (!other.limits_.isEmpty()) {
          if (limitsBuilder_.isEmpty()) {
            limitsBuilder_.dispose();
            limitsBuilder_ = null;
            limits_ = other.limits_;
            bitField0_ = (bitField0_ & ~0x00000001);
            limitsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getLimitsFieldBuilder() : null;
          } else {
            limitsBuilder_.addAllMessages(other.limits_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.client.app.fxLimit.GetLimitsByKeyResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.client.app.fxLimit.GetLimitsByKeyResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.client.app.fxLimit.Limit> limits_ =
      java.util.Collections.emptyList();
    private void ensureLimitsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        limits_ = new java.util.ArrayList<grpc.client.app.fxLimit.Limit>(limits_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.client.app.fxLimit.Limit, grpc.client.app.fxLimit.Limit.Builder, grpc.client.app.fxLimit.LimitOrBuilder> limitsBuilder_;

    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public java.util.List<grpc.client.app.fxLimit.Limit> getLimitsList() {
      if (limitsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(limits_);
      } else {
        return limitsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public int getLimitsCount() {
      if (limitsBuilder_ == null) {
        return limits_.size();
      } else {
        return limitsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public grpc.client.app.fxLimit.Limit getLimits(int index) {
      if (limitsBuilder_ == null) {
        return limits_.get(index);
      } else {
        return limitsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder setLimits(
        int index, grpc.client.app.fxLimit.Limit value) {
      if (limitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLimitsIsMutable();
        limits_.set(index, value);
        onChanged();
      } else {
        limitsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder setLimits(
        int index, grpc.client.app.fxLimit.Limit.Builder builderForValue) {
      if (limitsBuilder_ == null) {
        ensureLimitsIsMutable();
        limits_.set(index, builderForValue.build());
        onChanged();
      } else {
        limitsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder addLimits(grpc.client.app.fxLimit.Limit value) {
      if (limitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLimitsIsMutable();
        limits_.add(value);
        onChanged();
      } else {
        limitsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder addLimits(
        int index, grpc.client.app.fxLimit.Limit value) {
      if (limitsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLimitsIsMutable();
        limits_.add(index, value);
        onChanged();
      } else {
        limitsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder addLimits(
        grpc.client.app.fxLimit.Limit.Builder builderForValue) {
      if (limitsBuilder_ == null) {
        ensureLimitsIsMutable();
        limits_.add(builderForValue.build());
        onChanged();
      } else {
        limitsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder addLimits(
        int index, grpc.client.app.fxLimit.Limit.Builder builderForValue) {
      if (limitsBuilder_ == null) {
        ensureLimitsIsMutable();
        limits_.add(index, builderForValue.build());
        onChanged();
      } else {
        limitsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder addAllLimits(
        java.lang.Iterable<? extends grpc.client.app.fxLimit.Limit> values) {
      if (limitsBuilder_ == null) {
        ensureLimitsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, limits_);
        onChanged();
      } else {
        limitsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder clearLimits() {
      if (limitsBuilder_ == null) {
        limits_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        limitsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public Builder removeLimits(int index) {
      if (limitsBuilder_ == null) {
        ensureLimitsIsMutable();
        limits_.remove(index);
        onChanged();
      } else {
        limitsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public grpc.client.app.fxLimit.Limit.Builder getLimitsBuilder(
        int index) {
      return getLimitsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public grpc.client.app.fxLimit.LimitOrBuilder getLimitsOrBuilder(
        int index) {
      if (limitsBuilder_ == null) {
        return limits_.get(index);  } else {
        return limitsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public java.util.List<? extends grpc.client.app.fxLimit.LimitOrBuilder> 
         getLimitsOrBuilderList() {
      if (limitsBuilder_ != null) {
        return limitsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(limits_);
      }
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public grpc.client.app.fxLimit.Limit.Builder addLimitsBuilder() {
      return getLimitsFieldBuilder().addBuilder(
          grpc.client.app.fxLimit.Limit.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public grpc.client.app.fxLimit.Limit.Builder addLimitsBuilder(
        int index) {
      return getLimitsFieldBuilder().addBuilder(
          index, grpc.client.app.fxLimit.Limit.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc_limits.Limit limits = 1;</code>
     */
    public java.util.List<grpc.client.app.fxLimit.Limit.Builder> 
         getLimitsBuilderList() {
      return getLimitsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.client.app.fxLimit.Limit, grpc.client.app.fxLimit.Limit.Builder, grpc.client.app.fxLimit.LimitOrBuilder> 
        getLimitsFieldBuilder() {
      if (limitsBuilder_ == null) {
        limitsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.client.app.fxLimit.Limit, grpc.client.app.fxLimit.Limit.Builder, grpc.client.app.fxLimit.LimitOrBuilder>(
                limits_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        limits_ = null;
      }
      return limitsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc_limits.GetLimitsByKeyResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc_limits.GetLimitsByKeyResponse)
  private static final grpc.client.app.fxLimit.GetLimitsByKeyResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.client.app.fxLimit.GetLimitsByKeyResponse();
  }

  public static grpc.client.app.fxLimit.GetLimitsByKeyResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLimitsByKeyResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetLimitsByKeyResponse>() {
    @java.lang.Override
    public GetLimitsByKeyResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetLimitsByKeyResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetLimitsByKeyResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLimitsByKeyResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.client.app.fxLimit.GetLimitsByKeyResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

