// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

public interface LimitKeyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.LimitKey)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string customerDocument = 1;</code>
   */
  java.lang.String getCustomerDocument();
  /**
   * <code>string customerDocument = 1;</code>
   */
  com.google.protobuf.ByteString
      getCustomerDocumentBytes();

  /**
   * <code>string partnerID = 2;</code>
   */
  java.lang.String getPartnerID();
  /**
   * <code>string partnerID = 2;</code>
   */
  com.google.protobuf.ByteString
      getPartnerIDBytes();

  /**
   * <code>string offerID = 3;</code>
   */
  java.lang.String getOfferID();
  /**
   * <code>string offerID = 3;</code>
   */
  com.google.protobuf.ByteString
      getOfferIDBytes();

  /**
   * <code>.grpc_limits.Category category = 4;</code>
   */
  int getCategoryValue();
  /**
   * <code>.grpc_limits.Category category = 4;</code>
   */
  grpc.client.app.fxLimit.Category getCategory();

  /**
   * <code>.grpc_limits.LimitType type = 5;</code>
   */
  int getTypeValue();
  /**
   * <code>.grpc_limits.LimitType type = 5;</code>
   */
  grpc.client.app.fxLimit.LimitType getType();
}
