// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.client.app.fxLimit;

/**
 * <pre>
 * Limit filter
 * </pre>
 *
 * Protobuf enum {@code grpc_limits.RevokedFilter}
 */
public enum RevokedFilter
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ALL_LIMITS = 0;</code>
   */
  ALL_LIMITS(0),
  /**
   * <code>REVOKED = 1;</code>
   */
  REVOKED(1),
  /**
   * <code>NOT_REVOKED = 2;</code>
   */
  NOT_REVOKED(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ALL_LIMITS = 0;</code>
   */
  public static final int ALL_LIMITS_VALUE = 0;
  /**
   * <code>REVOKED = 1;</code>
   */
  public static final int REVOKED_VALUE = 1;
  /**
   * <code>NOT_REVOKED = 2;</code>
   */
  public static final int NOT_REVOKED_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RevokedFilter valueOf(int value) {
    return forNumber(value);
  }

  public static RevokedFilter forNumber(int value) {
    switch (value) {
      case 0: return ALL_LIMITS;
      case 1: return REVOKED;
      case 2: return NOT_REVOKED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RevokedFilter>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RevokedFilter> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RevokedFilter>() {
          public RevokedFilter findValueByNumber(int number) {
            return RevokedFilter.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return grpc.client.app.fxLimit.FxLimit.getDescriptor().getEnumTypes().get(4);
  }

  private static final RevokedFilter[] VALUES = values();

  public static RevokedFilter valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private RevokedFilter(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc_limits.RevokedFilter)
}

