// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

public interface AuthorshipOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.Authorship)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string author = 1;</code>
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 1;</code>
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string comment = 2;</code>
   */
  java.lang.String getComment();
  /**
   * <code>string comment = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommentBytes();
}
