// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

/**
 * <pre>
 * Event to Limit
 * </pre>
 *
 * Protobuf type {@code grpc_limits.Event}
 */
public  final class Event extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc_limits.Event)
    EventOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Event.newBuilder() to construct.
  private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Event() {
    id_ = "";
    type_ = 0;
    transactionType_ = 0;
    amount_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Event(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.server.app.fxLimit.Authorship.Builder subBuilder = null;
            if (authorship_ != null) {
              subBuilder = authorship_.toBuilder();
            }
            authorship_ = input.readMessage(grpc.server.app.fxLimit.Authorship.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(authorship_);
              authorship_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (date_ != null) {
              subBuilder = date_.toBuilder();
            }
            date_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(date_);
              date_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 42: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expirationDate_ != null) {
              subBuilder = expirationDate_.toBuilder();
            }
            expirationDate_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expirationDate_);
              expirationDate_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            transactionType_ = rawValue;
            break;
          }
          case 57: {

            amount_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Event_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Event_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.server.app.fxLimit.Event.class, grpc.server.app.fxLimit.Event.Builder.class);
  }

  public static final int AUTHORSHIP_FIELD_NUMBER = 1;
  private grpc.server.app.fxLimit.Authorship authorship_;
  /**
   * <code>.grpc_limits.Authorship authorship = 1;</code>
   */
  public boolean hasAuthorship() {
    return authorship_ != null;
  }
  /**
   * <code>.grpc_limits.Authorship authorship = 1;</code>
   */
  public grpc.server.app.fxLimit.Authorship getAuthorship() {
    return authorship_ == null ? grpc.server.app.fxLimit.Authorship.getDefaultInstance() : authorship_;
  }
  /**
   * <code>.grpc_limits.Authorship authorship = 1;</code>
   */
  public grpc.server.app.fxLimit.AuthorshipOrBuilder getAuthorshipOrBuilder() {
    return getAuthorship();
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATE_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp date_;
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  public boolean hasDate() {
    return date_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  public com.google.protobuf.Timestamp getDate() {
    return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
  }
  /**
   * <code>.google.protobuf.Timestamp date = 3;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
    return getDate();
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_;
  /**
   * <code>.grpc_limits.EventType type = 4;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.grpc_limits.EventType type = 4;</code>
   */
  public grpc.server.app.fxLimit.EventType getType() {
    @SuppressWarnings("deprecation")
    grpc.server.app.fxLimit.EventType result = grpc.server.app.fxLimit.EventType.valueOf(type_);
    return result == null ? grpc.server.app.fxLimit.EventType.UNRECOGNIZED : result;
  }

  public static final int EXPIRATIONDATE_FIELD_NUMBER = 5;
  private com.google.protobuf.Timestamp expirationDate_;
  /**
   * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
   */
  public boolean hasExpirationDate() {
    return expirationDate_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
   */
  public com.google.protobuf.Timestamp getExpirationDate() {
    return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
  }
  /**
   * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder() {
    return getExpirationDate();
  }

  public static final int TRANSACTIONTYPE_FIELD_NUMBER = 6;
  private int transactionType_;
  /**
   * <code>.grpc_limits.TransactionType transactionType = 6;</code>
   */
  public int getTransactionTypeValue() {
    return transactionType_;
  }
  /**
   * <code>.grpc_limits.TransactionType transactionType = 6;</code>
   */
  public grpc.server.app.fxLimit.TransactionType getTransactionType() {
    @SuppressWarnings("deprecation")
    grpc.server.app.fxLimit.TransactionType result = grpc.server.app.fxLimit.TransactionType.valueOf(transactionType_);
    return result == null ? grpc.server.app.fxLimit.TransactionType.UNRECOGNIZED : result;
  }

  public static final int AMOUNT_FIELD_NUMBER = 7;
  private double amount_;
  /**
   * <code>double amount = 7;</code>
   */
  public double getAmount() {
    return amount_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (authorship_ != null) {
      output.writeMessage(1, getAuthorship());
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (date_ != null) {
      output.writeMessage(3, getDate());
    }
    if (type_ != grpc.server.app.fxLimit.EventType.ALL_EVENTS.getNumber()) {
      output.writeEnum(4, type_);
    }
    if (expirationDate_ != null) {
      output.writeMessage(5, getExpirationDate());
    }
    if (transactionType_ != grpc.server.app.fxLimit.TransactionType.UNKNOWN_TRANSACTION.getNumber()) {
      output.writeEnum(6, transactionType_);
    }
    if (amount_ != 0D) {
      output.writeDouble(7, amount_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (authorship_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAuthorship());
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (date_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getDate());
    }
    if (type_ != grpc.server.app.fxLimit.EventType.ALL_EVENTS.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (expirationDate_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getExpirationDate());
    }
    if (transactionType_ != grpc.server.app.fxLimit.TransactionType.UNKNOWN_TRANSACTION.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, transactionType_);
    }
    if (amount_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, amount_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.server.app.fxLimit.Event)) {
      return super.equals(obj);
    }
    grpc.server.app.fxLimit.Event other = (grpc.server.app.fxLimit.Event) obj;

    boolean result = true;
    result = result && (hasAuthorship() == other.hasAuthorship());
    if (hasAuthorship()) {
      result = result && getAuthorship()
          .equals(other.getAuthorship());
    }
    result = result && getId()
        .equals(other.getId());
    result = result && (hasDate() == other.hasDate());
    if (hasDate()) {
      result = result && getDate()
          .equals(other.getDate());
    }
    result = result && type_ == other.type_;
    result = result && (hasExpirationDate() == other.hasExpirationDate());
    if (hasExpirationDate()) {
      result = result && getExpirationDate()
          .equals(other.getExpirationDate());
    }
    result = result && transactionType_ == other.transactionType_;
    result = result && (
        java.lang.Double.doubleToLongBits(getAmount())
        == java.lang.Double.doubleToLongBits(
            other.getAmount()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAuthorship()) {
      hash = (37 * hash) + AUTHORSHIP_FIELD_NUMBER;
      hash = (53 * hash) + getAuthorship().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasDate()) {
      hash = (37 * hash) + DATE_FIELD_NUMBER;
      hash = (53 * hash) + getDate().hashCode();
    }
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    if (hasExpirationDate()) {
      hash = (37 * hash) + EXPIRATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + getExpirationDate().hashCode();
    }
    hash = (37 * hash) + TRANSACTIONTYPE_FIELD_NUMBER;
    hash = (53 * hash) + transactionType_;
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getAmount()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.server.app.fxLimit.Event parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Event parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Event parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Event parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.server.app.fxLimit.Event prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Event to Limit
   * </pre>
   *
   * Protobuf type {@code grpc_limits.Event}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc_limits.Event)
      grpc.server.app.fxLimit.EventOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.server.app.fxLimit.Event.class, grpc.server.app.fxLimit.Event.Builder.class);
    }

    // Construct using grpc.server.app.fxLimit.Event.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (authorshipBuilder_ == null) {
        authorship_ = null;
      } else {
        authorship_ = null;
        authorshipBuilder_ = null;
      }
      id_ = "";

      if (dateBuilder_ == null) {
        date_ = null;
      } else {
        date_ = null;
        dateBuilder_ = null;
      }
      type_ = 0;

      if (expirationDateBuilder_ == null) {
        expirationDate_ = null;
      } else {
        expirationDate_ = null;
        expirationDateBuilder_ = null;
      }
      transactionType_ = 0;

      amount_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Event_descriptor;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Event getDefaultInstanceForType() {
      return grpc.server.app.fxLimit.Event.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Event build() {
      grpc.server.app.fxLimit.Event result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Event buildPartial() {
      grpc.server.app.fxLimit.Event result = new grpc.server.app.fxLimit.Event(this);
      if (authorshipBuilder_ == null) {
        result.authorship_ = authorship_;
      } else {
        result.authorship_ = authorshipBuilder_.build();
      }
      result.id_ = id_;
      if (dateBuilder_ == null) {
        result.date_ = date_;
      } else {
        result.date_ = dateBuilder_.build();
      }
      result.type_ = type_;
      if (expirationDateBuilder_ == null) {
        result.expirationDate_ = expirationDate_;
      } else {
        result.expirationDate_ = expirationDateBuilder_.build();
      }
      result.transactionType_ = transactionType_;
      result.amount_ = amount_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.server.app.fxLimit.Event) {
        return mergeFrom((grpc.server.app.fxLimit.Event)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.server.app.fxLimit.Event other) {
      if (other == grpc.server.app.fxLimit.Event.getDefaultInstance()) return this;
      if (other.hasAuthorship()) {
        mergeAuthorship(other.getAuthorship());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasDate()) {
        mergeDate(other.getDate());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.hasExpirationDate()) {
        mergeExpirationDate(other.getExpirationDate());
      }
      if (other.transactionType_ != 0) {
        setTransactionTypeValue(other.getTransactionTypeValue());
      }
      if (other.getAmount() != 0D) {
        setAmount(other.getAmount());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.server.app.fxLimit.Event parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.server.app.fxLimit.Event) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.server.app.fxLimit.Authorship authorship_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.Authorship, grpc.server.app.fxLimit.Authorship.Builder, grpc.server.app.fxLimit.AuthorshipOrBuilder> authorshipBuilder_;
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public boolean hasAuthorship() {
      return authorshipBuilder_ != null || authorship_ != null;
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public grpc.server.app.fxLimit.Authorship getAuthorship() {
      if (authorshipBuilder_ == null) {
        return authorship_ == null ? grpc.server.app.fxLimit.Authorship.getDefaultInstance() : authorship_;
      } else {
        return authorshipBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public Builder setAuthorship(grpc.server.app.fxLimit.Authorship value) {
      if (authorshipBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        authorship_ = value;
        onChanged();
      } else {
        authorshipBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public Builder setAuthorship(
        grpc.server.app.fxLimit.Authorship.Builder builderForValue) {
      if (authorshipBuilder_ == null) {
        authorship_ = builderForValue.build();
        onChanged();
      } else {
        authorshipBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public Builder mergeAuthorship(grpc.server.app.fxLimit.Authorship value) {
      if (authorshipBuilder_ == null) {
        if (authorship_ != null) {
          authorship_ =
            grpc.server.app.fxLimit.Authorship.newBuilder(authorship_).mergeFrom(value).buildPartial();
        } else {
          authorship_ = value;
        }
        onChanged();
      } else {
        authorshipBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public Builder clearAuthorship() {
      if (authorshipBuilder_ == null) {
        authorship_ = null;
        onChanged();
      } else {
        authorship_ = null;
        authorshipBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public grpc.server.app.fxLimit.Authorship.Builder getAuthorshipBuilder() {
      
      onChanged();
      return getAuthorshipFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    public grpc.server.app.fxLimit.AuthorshipOrBuilder getAuthorshipOrBuilder() {
      if (authorshipBuilder_ != null) {
        return authorshipBuilder_.getMessageOrBuilder();
      } else {
        return authorship_ == null ?
            grpc.server.app.fxLimit.Authorship.getDefaultInstance() : authorship_;
      }
    }
    /**
     * <code>.grpc_limits.Authorship authorship = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.Authorship, grpc.server.app.fxLimit.Authorship.Builder, grpc.server.app.fxLimit.AuthorshipOrBuilder> 
        getAuthorshipFieldBuilder() {
      if (authorshipBuilder_ == null) {
        authorshipBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.server.app.fxLimit.Authorship, grpc.server.app.fxLimit.Authorship.Builder, grpc.server.app.fxLimit.AuthorshipOrBuilder>(
                getAuthorship(),
                getParentForChildren(),
                isClean());
        authorship_ = null;
      }
      return authorshipBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp date_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> dateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public boolean hasDate() {
      return dateBuilder_ != null || date_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public com.google.protobuf.Timestamp getDate() {
      if (dateBuilder_ == null) {
        return date_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : date_;
      } else {
        return dateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public Builder setDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        date_ = value;
        onChanged();
      } else {
        dateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public Builder setDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (dateBuilder_ == null) {
        date_ = builderForValue.build();
        onChanged();
      } else {
        dateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public Builder mergeDate(com.google.protobuf.Timestamp value) {
      if (dateBuilder_ == null) {
        if (date_ != null) {
          date_ =
            com.google.protobuf.Timestamp.newBuilder(date_).mergeFrom(value).buildPartial();
        } else {
          date_ = value;
        }
        onChanged();
      } else {
        dateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public Builder clearDate() {
      if (dateBuilder_ == null) {
        date_ = null;
        onChanged();
      } else {
        date_ = null;
        dateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getDateBuilder() {
      
      onChanged();
      return getDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getDateOrBuilder() {
      if (dateBuilder_ != null) {
        return dateBuilder_.getMessageOrBuilder();
      } else {
        return date_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : date_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp date = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getDateFieldBuilder() {
      if (dateBuilder_ == null) {
        dateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getDate(),
                getParentForChildren(),
                isClean());
        date_ = null;
      }
      return dateBuilder_;
    }

    private int type_ = 0;
    /**
     * <code>.grpc_limits.EventType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.grpc_limits.EventType type = 4;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.EventType type = 4;</code>
     */
    public grpc.server.app.fxLimit.EventType getType() {
      @SuppressWarnings("deprecation")
      grpc.server.app.fxLimit.EventType result = grpc.server.app.fxLimit.EventType.valueOf(type_);
      return result == null ? grpc.server.app.fxLimit.EventType.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc_limits.EventType type = 4;</code>
     */
    public Builder setType(grpc.server.app.fxLimit.EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.EventType type = 4;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp expirationDate_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expirationDateBuilder_;
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public boolean hasExpirationDate() {
      return expirationDateBuilder_ != null || expirationDate_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public com.google.protobuf.Timestamp getExpirationDate() {
      if (expirationDateBuilder_ == null) {
        return expirationDate_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
      } else {
        return expirationDateBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public Builder setExpirationDate(com.google.protobuf.Timestamp value) {
      if (expirationDateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expirationDate_ = value;
        onChanged();
      } else {
        expirationDateBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public Builder setExpirationDate(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expirationDateBuilder_ == null) {
        expirationDate_ = builderForValue.build();
        onChanged();
      } else {
        expirationDateBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public Builder mergeExpirationDate(com.google.protobuf.Timestamp value) {
      if (expirationDateBuilder_ == null) {
        if (expirationDate_ != null) {
          expirationDate_ =
            com.google.protobuf.Timestamp.newBuilder(expirationDate_).mergeFrom(value).buildPartial();
        } else {
          expirationDate_ = value;
        }
        onChanged();
      } else {
        expirationDateBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public Builder clearExpirationDate() {
      if (expirationDateBuilder_ == null) {
        expirationDate_ = null;
        onChanged();
      } else {
        expirationDate_ = null;
        expirationDateBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpirationDateBuilder() {
      
      onChanged();
      return getExpirationDateFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpirationDateOrBuilder() {
      if (expirationDateBuilder_ != null) {
        return expirationDateBuilder_.getMessageOrBuilder();
      } else {
        return expirationDate_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expirationDate_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp expirationDate = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpirationDateFieldBuilder() {
      if (expirationDateBuilder_ == null) {
        expirationDateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpirationDate(),
                getParentForChildren(),
                isClean());
        expirationDate_ = null;
      }
      return expirationDateBuilder_;
    }

    private int transactionType_ = 0;
    /**
     * <code>.grpc_limits.TransactionType transactionType = 6;</code>
     */
    public int getTransactionTypeValue() {
      return transactionType_;
    }
    /**
     * <code>.grpc_limits.TransactionType transactionType = 6;</code>
     */
    public Builder setTransactionTypeValue(int value) {
      transactionType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.TransactionType transactionType = 6;</code>
     */
    public grpc.server.app.fxLimit.TransactionType getTransactionType() {
      @SuppressWarnings("deprecation")
      grpc.server.app.fxLimit.TransactionType result = grpc.server.app.fxLimit.TransactionType.valueOf(transactionType_);
      return result == null ? grpc.server.app.fxLimit.TransactionType.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc_limits.TransactionType transactionType = 6;</code>
     */
    public Builder setTransactionType(grpc.server.app.fxLimit.TransactionType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      transactionType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.TransactionType transactionType = 6;</code>
     */
    public Builder clearTransactionType() {
      
      transactionType_ = 0;
      onChanged();
      return this;
    }

    private double amount_ ;
    /**
     * <code>double amount = 7;</code>
     */
    public double getAmount() {
      return amount_;
    }
    /**
     * <code>double amount = 7;</code>
     */
    public Builder setAmount(double value) {
      
      amount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double amount = 7;</code>
     */
    public Builder clearAmount() {
      
      amount_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc_limits.Event)
  }

  // @@protoc_insertion_point(class_scope:grpc_limits.Event)
  private static final grpc.server.app.fxLimit.Event DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.server.app.fxLimit.Event();
  }

  public static grpc.server.app.fxLimit.Event getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Event>
      PARSER = new com.google.protobuf.AbstractParser<Event>() {
    @java.lang.Override
    public Event parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Event(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Event> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Event> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.server.app.fxLimit.Event getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

