// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

/**
 * <pre>
 * Limit Key
 * </pre>
 *
 * Protobuf type {@code grpc_limits.LimitKey}
 */
public  final class LimitKey extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc_limits.LimitKey)
    LimitKeyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LimitKey.newBuilder() to construct.
  private LimitKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LimitKey() {
    customerDocument_ = "";
    partnerID_ = "";
    offerID_ = "";
    category_ = 0;
    type_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LimitKey(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            customerDocument_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            partnerID_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            offerID_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            category_ = rawValue;
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_LimitKey_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_LimitKey_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.server.app.fxLimit.LimitKey.class, grpc.server.app.fxLimit.LimitKey.Builder.class);
  }

  public static final int CUSTOMERDOCUMENT_FIELD_NUMBER = 1;
  private volatile java.lang.Object customerDocument_;
  /**
   * <code>string customerDocument = 1;</code>
   */
  public java.lang.String getCustomerDocument() {
    java.lang.Object ref = customerDocument_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      customerDocument_ = s;
      return s;
    }
  }
  /**
   * <code>string customerDocument = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCustomerDocumentBytes() {
    java.lang.Object ref = customerDocument_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      customerDocument_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTNERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object partnerID_;
  /**
   * <code>string partnerID = 2;</code>
   */
  public java.lang.String getPartnerID() {
    java.lang.Object ref = partnerID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      partnerID_ = s;
      return s;
    }
  }
  /**
   * <code>string partnerID = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPartnerIDBytes() {
    java.lang.Object ref = partnerID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      partnerID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OFFERID_FIELD_NUMBER = 3;
  private volatile java.lang.Object offerID_;
  /**
   * <code>string offerID = 3;</code>
   */
  public java.lang.String getOfferID() {
    java.lang.Object ref = offerID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      offerID_ = s;
      return s;
    }
  }
  /**
   * <code>string offerID = 3;</code>
   */
  public com.google.protobuf.ByteString
      getOfferIDBytes() {
    java.lang.Object ref = offerID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      offerID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  private int category_;
  /**
   * <code>.grpc_limits.Category category = 4;</code>
   */
  public int getCategoryValue() {
    return category_;
  }
  /**
   * <code>.grpc_limits.Category category = 4;</code>
   */
  public grpc.server.app.fxLimit.Category getCategory() {
    @SuppressWarnings("deprecation")
    grpc.server.app.fxLimit.Category result = grpc.server.app.fxLimit.Category.valueOf(category_);
    return result == null ? grpc.server.app.fxLimit.Category.UNRECOGNIZED : result;
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private int type_;
  /**
   * <code>.grpc_limits.LimitType type = 5;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.grpc_limits.LimitType type = 5;</code>
   */
  public grpc.server.app.fxLimit.LimitType getType() {
    @SuppressWarnings("deprecation")
    grpc.server.app.fxLimit.LimitType result = grpc.server.app.fxLimit.LimitType.valueOf(type_);
    return result == null ? grpc.server.app.fxLimit.LimitType.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCustomerDocumentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, customerDocument_);
    }
    if (!getPartnerIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, partnerID_);
    }
    if (!getOfferIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, offerID_);
    }
    if (category_ != grpc.server.app.fxLimit.Category.UNKNOWN_CATEGORY.getNumber()) {
      output.writeEnum(4, category_);
    }
    if (type_ != grpc.server.app.fxLimit.LimitType.UNKNOWN_TYPE.getNumber()) {
      output.writeEnum(5, type_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCustomerDocumentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, customerDocument_);
    }
    if (!getPartnerIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, partnerID_);
    }
    if (!getOfferIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, offerID_);
    }
    if (category_ != grpc.server.app.fxLimit.Category.UNKNOWN_CATEGORY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, category_);
    }
    if (type_ != grpc.server.app.fxLimit.LimitType.UNKNOWN_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, type_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.server.app.fxLimit.LimitKey)) {
      return super.equals(obj);
    }
    grpc.server.app.fxLimit.LimitKey other = (grpc.server.app.fxLimit.LimitKey) obj;

    boolean result = true;
    result = result && getCustomerDocument()
        .equals(other.getCustomerDocument());
    result = result && getPartnerID()
        .equals(other.getPartnerID());
    result = result && getOfferID()
        .equals(other.getOfferID());
    result = result && category_ == other.category_;
    result = result && type_ == other.type_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CUSTOMERDOCUMENT_FIELD_NUMBER;
    hash = (53 * hash) + getCustomerDocument().hashCode();
    hash = (37 * hash) + PARTNERID_FIELD_NUMBER;
    hash = (53 * hash) + getPartnerID().hashCode();
    hash = (37 * hash) + OFFERID_FIELD_NUMBER;
    hash = (53 * hash) + getOfferID().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + category_;
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.LimitKey parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.LimitKey parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.LimitKey parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.server.app.fxLimit.LimitKey prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Limit Key
   * </pre>
   *
   * Protobuf type {@code grpc_limits.LimitKey}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc_limits.LimitKey)
      grpc.server.app.fxLimit.LimitKeyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_LimitKey_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_LimitKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.server.app.fxLimit.LimitKey.class, grpc.server.app.fxLimit.LimitKey.Builder.class);
    }

    // Construct using grpc.server.app.fxLimit.LimitKey.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      customerDocument_ = "";

      partnerID_ = "";

      offerID_ = "";

      category_ = 0;

      type_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_LimitKey_descriptor;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.LimitKey getDefaultInstanceForType() {
      return grpc.server.app.fxLimit.LimitKey.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.LimitKey build() {
      grpc.server.app.fxLimit.LimitKey result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.LimitKey buildPartial() {
      grpc.server.app.fxLimit.LimitKey result = new grpc.server.app.fxLimit.LimitKey(this);
      result.customerDocument_ = customerDocument_;
      result.partnerID_ = partnerID_;
      result.offerID_ = offerID_;
      result.category_ = category_;
      result.type_ = type_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.server.app.fxLimit.LimitKey) {
        return mergeFrom((grpc.server.app.fxLimit.LimitKey)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.server.app.fxLimit.LimitKey other) {
      if (other == grpc.server.app.fxLimit.LimitKey.getDefaultInstance()) return this;
      if (!other.getCustomerDocument().isEmpty()) {
        customerDocument_ = other.customerDocument_;
        onChanged();
      }
      if (!other.getPartnerID().isEmpty()) {
        partnerID_ = other.partnerID_;
        onChanged();
      }
      if (!other.getOfferID().isEmpty()) {
        offerID_ = other.offerID_;
        onChanged();
      }
      if (other.category_ != 0) {
        setCategoryValue(other.getCategoryValue());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.server.app.fxLimit.LimitKey parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.server.app.fxLimit.LimitKey) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object customerDocument_ = "";
    /**
     * <code>string customerDocument = 1;</code>
     */
    public java.lang.String getCustomerDocument() {
      java.lang.Object ref = customerDocument_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        customerDocument_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string customerDocument = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCustomerDocumentBytes() {
      java.lang.Object ref = customerDocument_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        customerDocument_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string customerDocument = 1;</code>
     */
    public Builder setCustomerDocument(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      customerDocument_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string customerDocument = 1;</code>
     */
    public Builder clearCustomerDocument() {
      
      customerDocument_ = getDefaultInstance().getCustomerDocument();
      onChanged();
      return this;
    }
    /**
     * <code>string customerDocument = 1;</code>
     */
    public Builder setCustomerDocumentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      customerDocument_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object partnerID_ = "";
    /**
     * <code>string partnerID = 2;</code>
     */
    public java.lang.String getPartnerID() {
      java.lang.Object ref = partnerID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partnerID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string partnerID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPartnerIDBytes() {
      java.lang.Object ref = partnerID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partnerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string partnerID = 2;</code>
     */
    public Builder setPartnerID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      partnerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string partnerID = 2;</code>
     */
    public Builder clearPartnerID() {
      
      partnerID_ = getDefaultInstance().getPartnerID();
      onChanged();
      return this;
    }
    /**
     * <code>string partnerID = 2;</code>
     */
    public Builder setPartnerIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      partnerID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object offerID_ = "";
    /**
     * <code>string offerID = 3;</code>
     */
    public java.lang.String getOfferID() {
      java.lang.Object ref = offerID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        offerID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string offerID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOfferIDBytes() {
      java.lang.Object ref = offerID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        offerID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string offerID = 3;</code>
     */
    public Builder setOfferID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      offerID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string offerID = 3;</code>
     */
    public Builder clearOfferID() {
      
      offerID_ = getDefaultInstance().getOfferID();
      onChanged();
      return this;
    }
    /**
     * <code>string offerID = 3;</code>
     */
    public Builder setOfferIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      offerID_ = value;
      onChanged();
      return this;
    }

    private int category_ = 0;
    /**
     * <code>.grpc_limits.Category category = 4;</code>
     */
    public int getCategoryValue() {
      return category_;
    }
    /**
     * <code>.grpc_limits.Category category = 4;</code>
     */
    public Builder setCategoryValue(int value) {
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.Category category = 4;</code>
     */
    public grpc.server.app.fxLimit.Category getCategory() {
      @SuppressWarnings("deprecation")
      grpc.server.app.fxLimit.Category result = grpc.server.app.fxLimit.Category.valueOf(category_);
      return result == null ? grpc.server.app.fxLimit.Category.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc_limits.Category category = 4;</code>
     */
    public Builder setCategory(grpc.server.app.fxLimit.Category value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      category_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.Category category = 4;</code>
     */
    public Builder clearCategory() {
      
      category_ = 0;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.grpc_limits.LimitType type = 5;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.grpc_limits.LimitType type = 5;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.LimitType type = 5;</code>
     */
    public grpc.server.app.fxLimit.LimitType getType() {
      @SuppressWarnings("deprecation")
      grpc.server.app.fxLimit.LimitType result = grpc.server.app.fxLimit.LimitType.valueOf(type_);
      return result == null ? grpc.server.app.fxLimit.LimitType.UNRECOGNIZED : result;
    }
    /**
     * <code>.grpc_limits.LimitType type = 5;</code>
     */
    public Builder setType(grpc.server.app.fxLimit.LimitType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.grpc_limits.LimitType type = 5;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc_limits.LimitKey)
  }

  // @@protoc_insertion_point(class_scope:grpc_limits.LimitKey)
  private static final grpc.server.app.fxLimit.LimitKey DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.server.app.fxLimit.LimitKey();
  }

  public static grpc.server.app.fxLimit.LimitKey getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LimitKey>
      PARSER = new com.google.protobuf.AbstractParser<LimitKey>() {
    @java.lang.Override
    public LimitKey parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LimitKey(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LimitKey> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LimitKey> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.server.app.fxLimit.LimitKey getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

