// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

/**
 * <pre>
 * Limit
 * </pre>
 *
 * Protobuf type {@code grpc_limits.Limit}
 */
public  final class Limit extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc_limits.Limit)
    LimitOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Limit.newBuilder() to construct.
  private Limit(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Limit() {
    id_ = "";
    revoked_ = false;
    events_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Limit(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.server.app.fxLimit.LimitKey.Builder subBuilder = null;
            if (limitKey_ != null) {
              subBuilder = limitKey_.toBuilder();
            }
            limitKey_ = input.readMessage(grpc.server.app.fxLimit.LimitKey.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(limitKey_);
              limitKey_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 26: {
            grpc.server.app.fxLimit.CurrencyAmount.Builder subBuilder = null;
            if (currencyAmount_ != null) {
              subBuilder = currencyAmount_.toBuilder();
            }
            currencyAmount_ = input.readMessage(grpc.server.app.fxLimit.CurrencyAmount.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currencyAmount_);
              currencyAmount_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            grpc.server.app.fxLimit.Balance.Builder subBuilder = null;
            if (balance_ != null) {
              subBuilder = balance_.toBuilder();
            }
            balance_ = input.readMessage(grpc.server.app.fxLimit.Balance.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(balance_);
              balance_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            grpc.server.app.fxLimit.Version.Builder subBuilder = null;
            if (version_ != null) {
              subBuilder = version_.toBuilder();
            }
            version_ = input.readMessage(grpc.server.app.fxLimit.Version.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(version_);
              version_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {

            revoked_ = input.readBool();
            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
              events_ = new java.util.ArrayList<grpc.server.app.fxLimit.Event>();
              mutable_bitField0_ |= 0x00000040;
            }
            events_.add(
                input.readMessage(grpc.server.app.fxLimit.Event.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
        events_ = java.util.Collections.unmodifiableList(events_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Limit_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Limit_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.server.app.fxLimit.Limit.class, grpc.server.app.fxLimit.Limit.Builder.class);
  }

  private int bitField0_;
  public static final int LIMITKEY_FIELD_NUMBER = 1;
  private grpc.server.app.fxLimit.LimitKey limitKey_;
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  public boolean hasLimitKey() {
    return limitKey_ != null;
  }
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  public grpc.server.app.fxLimit.LimitKey getLimitKey() {
    return limitKey_ == null ? grpc.server.app.fxLimit.LimitKey.getDefaultInstance() : limitKey_;
  }
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  public grpc.server.app.fxLimit.LimitKeyOrBuilder getLimitKeyOrBuilder() {
    return getLimitKey();
  }

  public static final int ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object id_;
  /**
   * <code>string id = 2;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENCYAMOUNT_FIELD_NUMBER = 3;
  private grpc.server.app.fxLimit.CurrencyAmount currencyAmount_;
  /**
   * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
   */
  public boolean hasCurrencyAmount() {
    return currencyAmount_ != null;
  }
  /**
   * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
   */
  public grpc.server.app.fxLimit.CurrencyAmount getCurrencyAmount() {
    return currencyAmount_ == null ? grpc.server.app.fxLimit.CurrencyAmount.getDefaultInstance() : currencyAmount_;
  }
  /**
   * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
   */
  public grpc.server.app.fxLimit.CurrencyAmountOrBuilder getCurrencyAmountOrBuilder() {
    return getCurrencyAmount();
  }

  public static final int BALANCE_FIELD_NUMBER = 4;
  private grpc.server.app.fxLimit.Balance balance_;
  /**
   * <code>.grpc_limits.Balance balance = 4;</code>
   */
  public boolean hasBalance() {
    return balance_ != null;
  }
  /**
   * <code>.grpc_limits.Balance balance = 4;</code>
   */
  public grpc.server.app.fxLimit.Balance getBalance() {
    return balance_ == null ? grpc.server.app.fxLimit.Balance.getDefaultInstance() : balance_;
  }
  /**
   * <code>.grpc_limits.Balance balance = 4;</code>
   */
  public grpc.server.app.fxLimit.BalanceOrBuilder getBalanceOrBuilder() {
    return getBalance();
  }

  public static final int VERSION_FIELD_NUMBER = 5;
  private grpc.server.app.fxLimit.Version version_;
  /**
   * <code>.grpc_limits.Version version = 5;</code>
   */
  public boolean hasVersion() {
    return version_ != null;
  }
  /**
   * <code>.grpc_limits.Version version = 5;</code>
   */
  public grpc.server.app.fxLimit.Version getVersion() {
    return version_ == null ? grpc.server.app.fxLimit.Version.getDefaultInstance() : version_;
  }
  /**
   * <code>.grpc_limits.Version version = 5;</code>
   */
  public grpc.server.app.fxLimit.VersionOrBuilder getVersionOrBuilder() {
    return getVersion();
  }

  public static final int REVOKED_FIELD_NUMBER = 6;
  private boolean revoked_;
  /**
   * <code>bool revoked = 6;</code>
   */
  public boolean getRevoked() {
    return revoked_;
  }

  public static final int EVENTS_FIELD_NUMBER = 7;
  private java.util.List<grpc.server.app.fxLimit.Event> events_;
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  public java.util.List<grpc.server.app.fxLimit.Event> getEventsList() {
    return events_;
  }
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  public java.util.List<? extends grpc.server.app.fxLimit.EventOrBuilder> 
      getEventsOrBuilderList() {
    return events_;
  }
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  public int getEventsCount() {
    return events_.size();
  }
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  public grpc.server.app.fxLimit.Event getEvents(int index) {
    return events_.get(index);
  }
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  public grpc.server.app.fxLimit.EventOrBuilder getEventsOrBuilder(
      int index) {
    return events_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (limitKey_ != null) {
      output.writeMessage(1, getLimitKey());
    }
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
    }
    if (currencyAmount_ != null) {
      output.writeMessage(3, getCurrencyAmount());
    }
    if (balance_ != null) {
      output.writeMessage(4, getBalance());
    }
    if (version_ != null) {
      output.writeMessage(5, getVersion());
    }
    if (revoked_ != false) {
      output.writeBool(6, revoked_);
    }
    for (int i = 0; i < events_.size(); i++) {
      output.writeMessage(7, events_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (limitKey_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLimitKey());
    }
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
    }
    if (currencyAmount_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getCurrencyAmount());
    }
    if (balance_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getBalance());
    }
    if (version_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getVersion());
    }
    if (revoked_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, revoked_);
    }
    for (int i = 0; i < events_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, events_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.server.app.fxLimit.Limit)) {
      return super.equals(obj);
    }
    grpc.server.app.fxLimit.Limit other = (grpc.server.app.fxLimit.Limit) obj;

    boolean result = true;
    result = result && (hasLimitKey() == other.hasLimitKey());
    if (hasLimitKey()) {
      result = result && getLimitKey()
          .equals(other.getLimitKey());
    }
    result = result && getId()
        .equals(other.getId());
    result = result && (hasCurrencyAmount() == other.hasCurrencyAmount());
    if (hasCurrencyAmount()) {
      result = result && getCurrencyAmount()
          .equals(other.getCurrencyAmount());
    }
    result = result && (hasBalance() == other.hasBalance());
    if (hasBalance()) {
      result = result && getBalance()
          .equals(other.getBalance());
    }
    result = result && (hasVersion() == other.hasVersion());
    if (hasVersion()) {
      result = result && getVersion()
          .equals(other.getVersion());
    }
    result = result && (getRevoked()
        == other.getRevoked());
    result = result && getEventsList()
        .equals(other.getEventsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLimitKey()) {
      hash = (37 * hash) + LIMITKEY_FIELD_NUMBER;
      hash = (53 * hash) + getLimitKey().hashCode();
    }
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    if (hasCurrencyAmount()) {
      hash = (37 * hash) + CURRENCYAMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCurrencyAmount().hashCode();
    }
    if (hasBalance()) {
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
    }
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
    }
    hash = (37 * hash) + REVOKED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRevoked());
    if (getEventsCount() > 0) {
      hash = (37 * hash) + EVENTS_FIELD_NUMBER;
      hash = (53 * hash) + getEventsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.server.app.fxLimit.Limit parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Limit parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Limit parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Limit parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.server.app.fxLimit.Limit prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Limit
   * </pre>
   *
   * Protobuf type {@code grpc_limits.Limit}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc_limits.Limit)
      grpc.server.app.fxLimit.LimitOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Limit_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Limit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.server.app.fxLimit.Limit.class, grpc.server.app.fxLimit.Limit.Builder.class);
    }

    // Construct using grpc.server.app.fxLimit.Limit.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEventsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (limitKeyBuilder_ == null) {
        limitKey_ = null;
      } else {
        limitKey_ = null;
        limitKeyBuilder_ = null;
      }
      id_ = "";

      if (currencyAmountBuilder_ == null) {
        currencyAmount_ = null;
      } else {
        currencyAmount_ = null;
        currencyAmountBuilder_ = null;
      }
      if (balanceBuilder_ == null) {
        balance_ = null;
      } else {
        balance_ = null;
        balanceBuilder_ = null;
      }
      if (versionBuilder_ == null) {
        version_ = null;
      } else {
        version_ = null;
        versionBuilder_ = null;
      }
      revoked_ = false;

      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Limit_descriptor;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Limit getDefaultInstanceForType() {
      return grpc.server.app.fxLimit.Limit.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Limit build() {
      grpc.server.app.fxLimit.Limit result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Limit buildPartial() {
      grpc.server.app.fxLimit.Limit result = new grpc.server.app.fxLimit.Limit(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (limitKeyBuilder_ == null) {
        result.limitKey_ = limitKey_;
      } else {
        result.limitKey_ = limitKeyBuilder_.build();
      }
      result.id_ = id_;
      if (currencyAmountBuilder_ == null) {
        result.currencyAmount_ = currencyAmount_;
      } else {
        result.currencyAmount_ = currencyAmountBuilder_.build();
      }
      if (balanceBuilder_ == null) {
        result.balance_ = balance_;
      } else {
        result.balance_ = balanceBuilder_.build();
      }
      if (versionBuilder_ == null) {
        result.version_ = version_;
      } else {
        result.version_ = versionBuilder_.build();
      }
      result.revoked_ = revoked_;
      if (eventsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          events_ = java.util.Collections.unmodifiableList(events_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.events_ = events_;
      } else {
        result.events_ = eventsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.server.app.fxLimit.Limit) {
        return mergeFrom((grpc.server.app.fxLimit.Limit)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.server.app.fxLimit.Limit other) {
      if (other == grpc.server.app.fxLimit.Limit.getDefaultInstance()) return this;
      if (other.hasLimitKey()) {
        mergeLimitKey(other.getLimitKey());
      }
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (other.hasCurrencyAmount()) {
        mergeCurrencyAmount(other.getCurrencyAmount());
      }
      if (other.hasBalance()) {
        mergeBalance(other.getBalance());
      }
      if (other.hasVersion()) {
        mergeVersion(other.getVersion());
      }
      if (other.getRevoked() != false) {
        setRevoked(other.getRevoked());
      }
      if (eventsBuilder_ == null) {
        if (!other.events_.isEmpty()) {
          if (events_.isEmpty()) {
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureEventsIsMutable();
            events_.addAll(other.events_);
          }
          onChanged();
        }
      } else {
        if (!other.events_.isEmpty()) {
          if (eventsBuilder_.isEmpty()) {
            eventsBuilder_.dispose();
            eventsBuilder_ = null;
            events_ = other.events_;
            bitField0_ = (bitField0_ & ~0x00000040);
            eventsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEventsFieldBuilder() : null;
          } else {
            eventsBuilder_.addAllMessages(other.events_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.server.app.fxLimit.Limit parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.server.app.fxLimit.Limit) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private grpc.server.app.fxLimit.LimitKey limitKey_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.LimitKey, grpc.server.app.fxLimit.LimitKey.Builder, grpc.server.app.fxLimit.LimitKeyOrBuilder> limitKeyBuilder_;
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public boolean hasLimitKey() {
      return limitKeyBuilder_ != null || limitKey_ != null;
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public grpc.server.app.fxLimit.LimitKey getLimitKey() {
      if (limitKeyBuilder_ == null) {
        return limitKey_ == null ? grpc.server.app.fxLimit.LimitKey.getDefaultInstance() : limitKey_;
      } else {
        return limitKeyBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public Builder setLimitKey(grpc.server.app.fxLimit.LimitKey value) {
      if (limitKeyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        limitKey_ = value;
        onChanged();
      } else {
        limitKeyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public Builder setLimitKey(
        grpc.server.app.fxLimit.LimitKey.Builder builderForValue) {
      if (limitKeyBuilder_ == null) {
        limitKey_ = builderForValue.build();
        onChanged();
      } else {
        limitKeyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public Builder mergeLimitKey(grpc.server.app.fxLimit.LimitKey value) {
      if (limitKeyBuilder_ == null) {
        if (limitKey_ != null) {
          limitKey_ =
            grpc.server.app.fxLimit.LimitKey.newBuilder(limitKey_).mergeFrom(value).buildPartial();
        } else {
          limitKey_ = value;
        }
        onChanged();
      } else {
        limitKeyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public Builder clearLimitKey() {
      if (limitKeyBuilder_ == null) {
        limitKey_ = null;
        onChanged();
      } else {
        limitKey_ = null;
        limitKeyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public grpc.server.app.fxLimit.LimitKey.Builder getLimitKeyBuilder() {
      
      onChanged();
      return getLimitKeyFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    public grpc.server.app.fxLimit.LimitKeyOrBuilder getLimitKeyOrBuilder() {
      if (limitKeyBuilder_ != null) {
        return limitKeyBuilder_.getMessageOrBuilder();
      } else {
        return limitKey_ == null ?
            grpc.server.app.fxLimit.LimitKey.getDefaultInstance() : limitKey_;
      }
    }
    /**
     * <code>.grpc_limits.LimitKey limitKey = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.LimitKey, grpc.server.app.fxLimit.LimitKey.Builder, grpc.server.app.fxLimit.LimitKeyOrBuilder> 
        getLimitKeyFieldBuilder() {
      if (limitKeyBuilder_ == null) {
        limitKeyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.server.app.fxLimit.LimitKey, grpc.server.app.fxLimit.LimitKey.Builder, grpc.server.app.fxLimit.LimitKeyOrBuilder>(
                getLimitKey(),
                getParentForChildren(),
                isClean());
        limitKey_ = null;
      }
      return limitKeyBuilder_;
    }

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 2;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <code>string id = 2;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private grpc.server.app.fxLimit.CurrencyAmount currencyAmount_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.CurrencyAmount, grpc.server.app.fxLimit.CurrencyAmount.Builder, grpc.server.app.fxLimit.CurrencyAmountOrBuilder> currencyAmountBuilder_;
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public boolean hasCurrencyAmount() {
      return currencyAmountBuilder_ != null || currencyAmount_ != null;
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public grpc.server.app.fxLimit.CurrencyAmount getCurrencyAmount() {
      if (currencyAmountBuilder_ == null) {
        return currencyAmount_ == null ? grpc.server.app.fxLimit.CurrencyAmount.getDefaultInstance() : currencyAmount_;
      } else {
        return currencyAmountBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public Builder setCurrencyAmount(grpc.server.app.fxLimit.CurrencyAmount value) {
      if (currencyAmountBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currencyAmount_ = value;
        onChanged();
      } else {
        currencyAmountBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public Builder setCurrencyAmount(
        grpc.server.app.fxLimit.CurrencyAmount.Builder builderForValue) {
      if (currencyAmountBuilder_ == null) {
        currencyAmount_ = builderForValue.build();
        onChanged();
      } else {
        currencyAmountBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public Builder mergeCurrencyAmount(grpc.server.app.fxLimit.CurrencyAmount value) {
      if (currencyAmountBuilder_ == null) {
        if (currencyAmount_ != null) {
          currencyAmount_ =
            grpc.server.app.fxLimit.CurrencyAmount.newBuilder(currencyAmount_).mergeFrom(value).buildPartial();
        } else {
          currencyAmount_ = value;
        }
        onChanged();
      } else {
        currencyAmountBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public Builder clearCurrencyAmount() {
      if (currencyAmountBuilder_ == null) {
        currencyAmount_ = null;
        onChanged();
      } else {
        currencyAmount_ = null;
        currencyAmountBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public grpc.server.app.fxLimit.CurrencyAmount.Builder getCurrencyAmountBuilder() {
      
      onChanged();
      return getCurrencyAmountFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    public grpc.server.app.fxLimit.CurrencyAmountOrBuilder getCurrencyAmountOrBuilder() {
      if (currencyAmountBuilder_ != null) {
        return currencyAmountBuilder_.getMessageOrBuilder();
      } else {
        return currencyAmount_ == null ?
            grpc.server.app.fxLimit.CurrencyAmount.getDefaultInstance() : currencyAmount_;
      }
    }
    /**
     * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.CurrencyAmount, grpc.server.app.fxLimit.CurrencyAmount.Builder, grpc.server.app.fxLimit.CurrencyAmountOrBuilder> 
        getCurrencyAmountFieldBuilder() {
      if (currencyAmountBuilder_ == null) {
        currencyAmountBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.server.app.fxLimit.CurrencyAmount, grpc.server.app.fxLimit.CurrencyAmount.Builder, grpc.server.app.fxLimit.CurrencyAmountOrBuilder>(
                getCurrencyAmount(),
                getParentForChildren(),
                isClean());
        currencyAmount_ = null;
      }
      return currencyAmountBuilder_;
    }

    private grpc.server.app.fxLimit.Balance balance_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.Balance, grpc.server.app.fxLimit.Balance.Builder, grpc.server.app.fxLimit.BalanceOrBuilder> balanceBuilder_;
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public boolean hasBalance() {
      return balanceBuilder_ != null || balance_ != null;
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public grpc.server.app.fxLimit.Balance getBalance() {
      if (balanceBuilder_ == null) {
        return balance_ == null ? grpc.server.app.fxLimit.Balance.getDefaultInstance() : balance_;
      } else {
        return balanceBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public Builder setBalance(grpc.server.app.fxLimit.Balance value) {
      if (balanceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        balance_ = value;
        onChanged();
      } else {
        balanceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public Builder setBalance(
        grpc.server.app.fxLimit.Balance.Builder builderForValue) {
      if (balanceBuilder_ == null) {
        balance_ = builderForValue.build();
        onChanged();
      } else {
        balanceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public Builder mergeBalance(grpc.server.app.fxLimit.Balance value) {
      if (balanceBuilder_ == null) {
        if (balance_ != null) {
          balance_ =
            grpc.server.app.fxLimit.Balance.newBuilder(balance_).mergeFrom(value).buildPartial();
        } else {
          balance_ = value;
        }
        onChanged();
      } else {
        balanceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public Builder clearBalance() {
      if (balanceBuilder_ == null) {
        balance_ = null;
        onChanged();
      } else {
        balance_ = null;
        balanceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public grpc.server.app.fxLimit.Balance.Builder getBalanceBuilder() {
      
      onChanged();
      return getBalanceFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    public grpc.server.app.fxLimit.BalanceOrBuilder getBalanceOrBuilder() {
      if (balanceBuilder_ != null) {
        return balanceBuilder_.getMessageOrBuilder();
      } else {
        return balance_ == null ?
            grpc.server.app.fxLimit.Balance.getDefaultInstance() : balance_;
      }
    }
    /**
     * <code>.grpc_limits.Balance balance = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.Balance, grpc.server.app.fxLimit.Balance.Builder, grpc.server.app.fxLimit.BalanceOrBuilder> 
        getBalanceFieldBuilder() {
      if (balanceBuilder_ == null) {
        balanceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.server.app.fxLimit.Balance, grpc.server.app.fxLimit.Balance.Builder, grpc.server.app.fxLimit.BalanceOrBuilder>(
                getBalance(),
                getParentForChildren(),
                isClean());
        balance_ = null;
      }
      return balanceBuilder_;
    }

    private grpc.server.app.fxLimit.Version version_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.Version, grpc.server.app.fxLimit.Version.Builder, grpc.server.app.fxLimit.VersionOrBuilder> versionBuilder_;
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public boolean hasVersion() {
      return versionBuilder_ != null || version_ != null;
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public grpc.server.app.fxLimit.Version getVersion() {
      if (versionBuilder_ == null) {
        return version_ == null ? grpc.server.app.fxLimit.Version.getDefaultInstance() : version_;
      } else {
        return versionBuilder_.getMessage();
      }
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public Builder setVersion(grpc.server.app.fxLimit.Version value) {
      if (versionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        version_ = value;
        onChanged();
      } else {
        versionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public Builder setVersion(
        grpc.server.app.fxLimit.Version.Builder builderForValue) {
      if (versionBuilder_ == null) {
        version_ = builderForValue.build();
        onChanged();
      } else {
        versionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public Builder mergeVersion(grpc.server.app.fxLimit.Version value) {
      if (versionBuilder_ == null) {
        if (version_ != null) {
          version_ =
            grpc.server.app.fxLimit.Version.newBuilder(version_).mergeFrom(value).buildPartial();
        } else {
          version_ = value;
        }
        onChanged();
      } else {
        versionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public Builder clearVersion() {
      if (versionBuilder_ == null) {
        version_ = null;
        onChanged();
      } else {
        version_ = null;
        versionBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public grpc.server.app.fxLimit.Version.Builder getVersionBuilder() {
      
      onChanged();
      return getVersionFieldBuilder().getBuilder();
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    public grpc.server.app.fxLimit.VersionOrBuilder getVersionOrBuilder() {
      if (versionBuilder_ != null) {
        return versionBuilder_.getMessageOrBuilder();
      } else {
        return version_ == null ?
            grpc.server.app.fxLimit.Version.getDefaultInstance() : version_;
      }
    }
    /**
     * <code>.grpc_limits.Version version = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.server.app.fxLimit.Version, grpc.server.app.fxLimit.Version.Builder, grpc.server.app.fxLimit.VersionOrBuilder> 
        getVersionFieldBuilder() {
      if (versionBuilder_ == null) {
        versionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.server.app.fxLimit.Version, grpc.server.app.fxLimit.Version.Builder, grpc.server.app.fxLimit.VersionOrBuilder>(
                getVersion(),
                getParentForChildren(),
                isClean());
        version_ = null;
      }
      return versionBuilder_;
    }

    private boolean revoked_ ;
    /**
     * <code>bool revoked = 6;</code>
     */
    public boolean getRevoked() {
      return revoked_;
    }
    /**
     * <code>bool revoked = 6;</code>
     */
    public Builder setRevoked(boolean value) {
      
      revoked_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool revoked = 6;</code>
     */
    public Builder clearRevoked() {
      
      revoked_ = false;
      onChanged();
      return this;
    }

    private java.util.List<grpc.server.app.fxLimit.Event> events_ =
      java.util.Collections.emptyList();
    private void ensureEventsIsMutable() {
      if (!((bitField0_ & 0x00000040) == 0x00000040)) {
        events_ = new java.util.ArrayList<grpc.server.app.fxLimit.Event>(events_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.server.app.fxLimit.Event, grpc.server.app.fxLimit.Event.Builder, grpc.server.app.fxLimit.EventOrBuilder> eventsBuilder_;

    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public java.util.List<grpc.server.app.fxLimit.Event> getEventsList() {
      if (eventsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(events_);
      } else {
        return eventsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public int getEventsCount() {
      if (eventsBuilder_ == null) {
        return events_.size();
      } else {
        return eventsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public grpc.server.app.fxLimit.Event getEvents(int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);
      } else {
        return eventsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder setEvents(
        int index, grpc.server.app.fxLimit.Event value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.set(index, value);
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder setEvents(
        int index, grpc.server.app.fxLimit.Event.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.set(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder addEvents(grpc.server.app.fxLimit.Event value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder addEvents(
        int index, grpc.server.app.fxLimit.Event value) {
      if (eventsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEventsIsMutable();
        events_.add(index, value);
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder addEvents(
        grpc.server.app.fxLimit.Event.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder addEvents(
        int index, grpc.server.app.fxLimit.Event.Builder builderForValue) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.add(index, builderForValue.build());
        onChanged();
      } else {
        eventsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder addAllEvents(
        java.lang.Iterable<? extends grpc.server.app.fxLimit.Event> values) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, events_);
        onChanged();
      } else {
        eventsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder clearEvents() {
      if (eventsBuilder_ == null) {
        events_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        eventsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public Builder removeEvents(int index) {
      if (eventsBuilder_ == null) {
        ensureEventsIsMutable();
        events_.remove(index);
        onChanged();
      } else {
        eventsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public grpc.server.app.fxLimit.Event.Builder getEventsBuilder(
        int index) {
      return getEventsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public grpc.server.app.fxLimit.EventOrBuilder getEventsOrBuilder(
        int index) {
      if (eventsBuilder_ == null) {
        return events_.get(index);  } else {
        return eventsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public java.util.List<? extends grpc.server.app.fxLimit.EventOrBuilder> 
         getEventsOrBuilderList() {
      if (eventsBuilder_ != null) {
        return eventsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(events_);
      }
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public grpc.server.app.fxLimit.Event.Builder addEventsBuilder() {
      return getEventsFieldBuilder().addBuilder(
          grpc.server.app.fxLimit.Event.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public grpc.server.app.fxLimit.Event.Builder addEventsBuilder(
        int index) {
      return getEventsFieldBuilder().addBuilder(
          index, grpc.server.app.fxLimit.Event.getDefaultInstance());
    }
    /**
     * <code>repeated .grpc_limits.Event events = 7;</code>
     */
    public java.util.List<grpc.server.app.fxLimit.Event.Builder> 
         getEventsBuilderList() {
      return getEventsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.server.app.fxLimit.Event, grpc.server.app.fxLimit.Event.Builder, grpc.server.app.fxLimit.EventOrBuilder> 
        getEventsFieldBuilder() {
      if (eventsBuilder_ == null) {
        eventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.server.app.fxLimit.Event, grpc.server.app.fxLimit.Event.Builder, grpc.server.app.fxLimit.EventOrBuilder>(
                events_,
                ((bitField0_ & 0x00000040) == 0x00000040),
                getParentForChildren(),
                isClean());
        events_ = null;
      }
      return eventsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc_limits.Limit)
  }

  // @@protoc_insertion_point(class_scope:grpc_limits.Limit)
  private static final grpc.server.app.fxLimit.Limit DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.server.app.fxLimit.Limit();
  }

  public static grpc.server.app.fxLimit.Limit getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Limit>
      PARSER = new com.google.protobuf.AbstractParser<Limit>() {
    @java.lang.Override
    public Limit parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Limit(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Limit> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Limit> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.server.app.fxLimit.Limit getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

