// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

public interface LimitOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.Limit)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  boolean hasLimitKey();
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  grpc.server.app.fxLimit.LimitKey getLimitKey();
  /**
   * <code>.grpc_limits.LimitKey limitKey = 1;</code>
   */
  grpc.server.app.fxLimit.LimitKeyOrBuilder getLimitKeyOrBuilder();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
   */
  boolean hasCurrencyAmount();
  /**
   * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
   */
  grpc.server.app.fxLimit.CurrencyAmount getCurrencyAmount();
  /**
   * <code>.grpc_limits.CurrencyAmount currencyAmount = 3;</code>
   */
  grpc.server.app.fxLimit.CurrencyAmountOrBuilder getCurrencyAmountOrBuilder();

  /**
   * <code>.grpc_limits.Balance balance = 4;</code>
   */
  boolean hasBalance();
  /**
   * <code>.grpc_limits.Balance balance = 4;</code>
   */
  grpc.server.app.fxLimit.Balance getBalance();
  /**
   * <code>.grpc_limits.Balance balance = 4;</code>
   */
  grpc.server.app.fxLimit.BalanceOrBuilder getBalanceOrBuilder();

  /**
   * <code>.grpc_limits.Version version = 5;</code>
   */
  boolean hasVersion();
  /**
   * <code>.grpc_limits.Version version = 5;</code>
   */
  grpc.server.app.fxLimit.Version getVersion();
  /**
   * <code>.grpc_limits.Version version = 5;</code>
   */
  grpc.server.app.fxLimit.VersionOrBuilder getVersionOrBuilder();

  /**
   * <code>bool revoked = 6;</code>
   */
  boolean getRevoked();

  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  java.util.List<grpc.server.app.fxLimit.Event> 
      getEventsList();
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  grpc.server.app.fxLimit.Event getEvents(int index);
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  int getEventsCount();
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  java.util.List<? extends grpc.server.app.fxLimit.EventOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <code>repeated .grpc_limits.Event events = 7;</code>
   */
  grpc.server.app.fxLimit.EventOrBuilder getEventsOrBuilder(
      int index);
}
