// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

public interface PaginatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc_limits.Paginator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 limit = 1;</code>
   */
  long getLimit();

  /**
   * <code>int64 offset = 2;</code>
   */
  long getOffset();
}
