// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

/**
 * <pre>
 * Transaction types
 * </pre>
 *
 * Protobuf enum {@code grpc_limits.TransactionType}
 */
public enum TransactionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_TRANSACTION = 0;</code>
   */
  UNKNOWN_TRANSACTION(0),
  /**
   * <code>DEBIT_TRANSACTION = 1;</code>
   */
  DEBIT_TRANSACTION(1),
  /**
   * <code>CREDIT_TRANSACTION = 2;</code>
   */
  CREDIT_TRANSACTION(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_TRANSACTION = 0;</code>
   */
  public static final int UNKNOWN_TRANSACTION_VALUE = 0;
  /**
   * <code>DEBIT_TRANSACTION = 1;</code>
   */
  public static final int DEBIT_TRANSACTION_VALUE = 1;
  /**
   * <code>CREDIT_TRANSACTION = 2;</code>
   */
  public static final int CREDIT_TRANSACTION_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TransactionType valueOf(int value) {
    return forNumber(value);
  }

  public static TransactionType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_TRANSACTION;
      case 1: return DEBIT_TRANSACTION;
      case 2: return CREDIT_TRANSACTION;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TransactionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TransactionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TransactionType>() {
          public TransactionType findValueByNumber(int number) {
            return TransactionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return grpc.server.app.fxLimit.FxLimit.getDescriptor().getEnumTypes().get(2);
  }

  private static final TransactionType[] VALUES = values();

  public static TransactionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TransactionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:grpc_limits.TransactionType)
}

