// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fxLimit.proto

package grpc.server.app.fxLimit;

/**
 * <pre>
 * Version to Limit
 * </pre>
 *
 * Protobuf type {@code grpc_limits.Version}
 */
public  final class Version extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:grpc_limits.Version)
    VersionOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Version.newBuilder() to construct.
  private Version(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Version() {
    createdBy_ = "";
    lastUpdatedBy_ = "";
    number_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Version(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            createdBy_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (createdAt_ != null) {
              subBuilder = createdAt_.toBuilder();
            }
            createdAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(createdAt_);
              createdAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            lastUpdatedBy_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (lastUpdatedAt_ != null) {
              subBuilder = lastUpdatedAt_.toBuilder();
            }
            lastUpdatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(lastUpdatedAt_);
              lastUpdatedAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 40: {

            number_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Version_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Version_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.server.app.fxLimit.Version.class, grpc.server.app.fxLimit.Version.Builder.class);
  }

  public static final int CREATEDBY_FIELD_NUMBER = 1;
  private volatile java.lang.Object createdBy_;
  /**
   * <code>string createdBy = 1;</code>
   */
  public java.lang.String getCreatedBy() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdBy_ = s;
      return s;
    }
  }
  /**
   * <code>string createdBy = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedByBytes() {
    java.lang.Object ref = createdBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDAT_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp createdAt_;
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   */
  public boolean hasCreatedAt() {
    return createdAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   */
  public com.google.protobuf.Timestamp getCreatedAt() {
    return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp createdAt = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
    return getCreatedAt();
  }

  public static final int LASTUPDATEDBY_FIELD_NUMBER = 3;
  private volatile java.lang.Object lastUpdatedBy_;
  /**
   * <code>string lastUpdatedBy = 3;</code>
   */
  public java.lang.String getLastUpdatedBy() {
    java.lang.Object ref = lastUpdatedBy_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastUpdatedBy_ = s;
      return s;
    }
  }
  /**
   * <code>string lastUpdatedBy = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLastUpdatedByBytes() {
    java.lang.Object ref = lastUpdatedBy_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastUpdatedBy_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LASTUPDATEDAT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp lastUpdatedAt_;
  /**
   * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
   */
  public boolean hasLastUpdatedAt() {
    return lastUpdatedAt_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
   */
  public com.google.protobuf.Timestamp getLastUpdatedAt() {
    return lastUpdatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedAt_;
  }
  /**
   * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getLastUpdatedAtOrBuilder() {
    return getLastUpdatedAt();
  }

  public static final int NUMBER_FIELD_NUMBER = 5;
  private int number_;
  /**
   * <code>int32 number = 5;</code>
   */
  public int getNumber() {
    return number_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCreatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, createdBy_);
    }
    if (createdAt_ != null) {
      output.writeMessage(2, getCreatedAt());
    }
    if (!getLastUpdatedByBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastUpdatedBy_);
    }
    if (lastUpdatedAt_ != null) {
      output.writeMessage(4, getLastUpdatedAt());
    }
    if (number_ != 0) {
      output.writeInt32(5, number_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCreatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, createdBy_);
    }
    if (createdAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreatedAt());
    }
    if (!getLastUpdatedByBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastUpdatedBy_);
    }
    if (lastUpdatedAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLastUpdatedAt());
    }
    if (number_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, number_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.server.app.fxLimit.Version)) {
      return super.equals(obj);
    }
    grpc.server.app.fxLimit.Version other = (grpc.server.app.fxLimit.Version) obj;

    boolean result = true;
    result = result && getCreatedBy()
        .equals(other.getCreatedBy());
    result = result && (hasCreatedAt() == other.hasCreatedAt());
    if (hasCreatedAt()) {
      result = result && getCreatedAt()
          .equals(other.getCreatedAt());
    }
    result = result && getLastUpdatedBy()
        .equals(other.getLastUpdatedBy());
    result = result && (hasLastUpdatedAt() == other.hasLastUpdatedAt());
    if (hasLastUpdatedAt()) {
      result = result && getLastUpdatedAt()
          .equals(other.getLastUpdatedAt());
    }
    result = result && (getNumber()
        == other.getNumber());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CREATEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedBy().hashCode();
    if (hasCreatedAt()) {
      hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getCreatedAt().hashCode();
    }
    hash = (37 * hash) + LASTUPDATEDBY_FIELD_NUMBER;
    hash = (53 * hash) + getLastUpdatedBy().hashCode();
    if (hasLastUpdatedAt()) {
      hash = (37 * hash) + LASTUPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdatedAt().hashCode();
    }
    hash = (37 * hash) + NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getNumber();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.server.app.fxLimit.Version parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Version parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Version parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.server.app.fxLimit.Version parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.server.app.fxLimit.Version prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Version to Limit
   * </pre>
   *
   * Protobuf type {@code grpc_limits.Version}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc_limits.Version)
      grpc.server.app.fxLimit.VersionOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Version_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Version_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.server.app.fxLimit.Version.class, grpc.server.app.fxLimit.Version.Builder.class);
    }

    // Construct using grpc.server.app.fxLimit.Version.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      createdBy_ = "";

      if (createdAtBuilder_ == null) {
        createdAt_ = null;
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }
      lastUpdatedBy_ = "";

      if (lastUpdatedAtBuilder_ == null) {
        lastUpdatedAt_ = null;
      } else {
        lastUpdatedAt_ = null;
        lastUpdatedAtBuilder_ = null;
      }
      number_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.server.app.fxLimit.FxLimit.internal_static_grpc_limits_Version_descriptor;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Version getDefaultInstanceForType() {
      return grpc.server.app.fxLimit.Version.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Version build() {
      grpc.server.app.fxLimit.Version result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.server.app.fxLimit.Version buildPartial() {
      grpc.server.app.fxLimit.Version result = new grpc.server.app.fxLimit.Version(this);
      result.createdBy_ = createdBy_;
      if (createdAtBuilder_ == null) {
        result.createdAt_ = createdAt_;
      } else {
        result.createdAt_ = createdAtBuilder_.build();
      }
      result.lastUpdatedBy_ = lastUpdatedBy_;
      if (lastUpdatedAtBuilder_ == null) {
        result.lastUpdatedAt_ = lastUpdatedAt_;
      } else {
        result.lastUpdatedAt_ = lastUpdatedAtBuilder_.build();
      }
      result.number_ = number_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.server.app.fxLimit.Version) {
        return mergeFrom((grpc.server.app.fxLimit.Version)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.server.app.fxLimit.Version other) {
      if (other == grpc.server.app.fxLimit.Version.getDefaultInstance()) return this;
      if (!other.getCreatedBy().isEmpty()) {
        createdBy_ = other.createdBy_;
        onChanged();
      }
      if (other.hasCreatedAt()) {
        mergeCreatedAt(other.getCreatedAt());
      }
      if (!other.getLastUpdatedBy().isEmpty()) {
        lastUpdatedBy_ = other.lastUpdatedBy_;
        onChanged();
      }
      if (other.hasLastUpdatedAt()) {
        mergeLastUpdatedAt(other.getLastUpdatedAt());
      }
      if (other.getNumber() != 0) {
        setNumber(other.getNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.server.app.fxLimit.Version parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.server.app.fxLimit.Version) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object createdBy_ = "";
    /**
     * <code>string createdBy = 1;</code>
     */
    public java.lang.String getCreatedBy() {
      java.lang.Object ref = createdBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string createdBy = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedByBytes() {
      java.lang.Object ref = createdBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string createdBy = 1;</code>
     */
    public Builder setCreatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string createdBy = 1;</code>
     */
    public Builder clearCreatedBy() {
      
      createdBy_ = getDefaultInstance().getCreatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string createdBy = 1;</code>
     */
    public Builder setCreatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdBy_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createdAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public boolean hasCreatedAt() {
      return createdAtBuilder_ != null || createdAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public com.google.protobuf.Timestamp getCreatedAt() {
      if (createdAtBuilder_ == null) {
        return createdAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      } else {
        return createdAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder setCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createdAt_ = value;
        onChanged();
      } else {
        createdAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder setCreatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createdAtBuilder_ == null) {
        createdAt_ = builderForValue.build();
        onChanged();
      } else {
        createdAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder mergeCreatedAt(com.google.protobuf.Timestamp value) {
      if (createdAtBuilder_ == null) {
        if (createdAt_ != null) {
          createdAt_ =
            com.google.protobuf.Timestamp.newBuilder(createdAt_).mergeFrom(value).buildPartial();
        } else {
          createdAt_ = value;
        }
        onChanged();
      } else {
        createdAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public Builder clearCreatedAt() {
      if (createdAtBuilder_ == null) {
        createdAt_ = null;
        onChanged();
      } else {
        createdAt_ = null;
        createdAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreatedAtBuilder() {
      
      onChanged();
      return getCreatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedAtOrBuilder() {
      if (createdAtBuilder_ != null) {
        return createdAtBuilder_.getMessageOrBuilder();
      } else {
        return createdAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createdAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp createdAt = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreatedAtFieldBuilder() {
      if (createdAtBuilder_ == null) {
        createdAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreatedAt(),
                getParentForChildren(),
                isClean());
        createdAt_ = null;
      }
      return createdAtBuilder_;
    }

    private java.lang.Object lastUpdatedBy_ = "";
    /**
     * <code>string lastUpdatedBy = 3;</code>
     */
    public java.lang.String getLastUpdatedBy() {
      java.lang.Object ref = lastUpdatedBy_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastUpdatedBy_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string lastUpdatedBy = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLastUpdatedByBytes() {
      java.lang.Object ref = lastUpdatedBy_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastUpdatedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string lastUpdatedBy = 3;</code>
     */
    public Builder setLastUpdatedBy(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastUpdatedBy_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string lastUpdatedBy = 3;</code>
     */
    public Builder clearLastUpdatedBy() {
      
      lastUpdatedBy_ = getDefaultInstance().getLastUpdatedBy();
      onChanged();
      return this;
    }
    /**
     * <code>string lastUpdatedBy = 3;</code>
     */
    public Builder setLastUpdatedByBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastUpdatedBy_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp lastUpdatedAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastUpdatedAtBuilder_;
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public boolean hasLastUpdatedAt() {
      return lastUpdatedAtBuilder_ != null || lastUpdatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public com.google.protobuf.Timestamp getLastUpdatedAt() {
      if (lastUpdatedAtBuilder_ == null) {
        return lastUpdatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedAt_;
      } else {
        return lastUpdatedAtBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public Builder setLastUpdatedAt(com.google.protobuf.Timestamp value) {
      if (lastUpdatedAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastUpdatedAt_ = value;
        onChanged();
      } else {
        lastUpdatedAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public Builder setLastUpdatedAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (lastUpdatedAtBuilder_ == null) {
        lastUpdatedAt_ = builderForValue.build();
        onChanged();
      } else {
        lastUpdatedAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public Builder mergeLastUpdatedAt(com.google.protobuf.Timestamp value) {
      if (lastUpdatedAtBuilder_ == null) {
        if (lastUpdatedAt_ != null) {
          lastUpdatedAt_ =
            com.google.protobuf.Timestamp.newBuilder(lastUpdatedAt_).mergeFrom(value).buildPartial();
        } else {
          lastUpdatedAt_ = value;
        }
        onChanged();
      } else {
        lastUpdatedAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public Builder clearLastUpdatedAt() {
      if (lastUpdatedAtBuilder_ == null) {
        lastUpdatedAt_ = null;
        onChanged();
      } else {
        lastUpdatedAt_ = null;
        lastUpdatedAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLastUpdatedAtBuilder() {
      
      onChanged();
      return getLastUpdatedAtFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLastUpdatedAtOrBuilder() {
      if (lastUpdatedAtBuilder_ != null) {
        return lastUpdatedAtBuilder_.getMessageOrBuilder();
      } else {
        return lastUpdatedAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : lastUpdatedAt_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp lastUpdatedAt = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLastUpdatedAtFieldBuilder() {
      if (lastUpdatedAtBuilder_ == null) {
        lastUpdatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLastUpdatedAt(),
                getParentForChildren(),
                isClean());
        lastUpdatedAt_ = null;
      }
      return lastUpdatedAtBuilder_;
    }

    private int number_ ;
    /**
     * <code>int32 number = 5;</code>
     */
    public int getNumber() {
      return number_;
    }
    /**
     * <code>int32 number = 5;</code>
     */
    public Builder setNumber(int value) {
      
      number_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 number = 5;</code>
     */
    public Builder clearNumber() {
      
      number_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:grpc_limits.Version)
  }

  // @@protoc_insertion_point(class_scope:grpc_limits.Version)
  private static final grpc.server.app.fxLimit.Version DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.server.app.fxLimit.Version();
  }

  public static grpc.server.app.fxLimit.Version getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Version>
      PARSER = new com.google.protobuf.AbstractParser<Version>() {
    @java.lang.Override
    public Version parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Version(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Version> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Version> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.server.app.fxLimit.Version getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

